// balloons: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'balloons',
  about: 'hot air balloons over green hills at sunrise',
  seed: 51,
  transition: null,
  graph: {
    let: { cellBlue: 6, cellPink: 5.6, cellYellow: 6.4, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      frame: { type: 'rect', params: { x: 0, y: 0, w: 1080, h: 1080 } },
      // sunrise sky: pink and blue dots at the top, yellow below, paper around the sun
      skyY: { type: 'field', params: { expr: 'clamp(0.2 + 0.95*lin(@x,@y,0,60,0,400) - 1.4*pow(radial(@x,@y,720,590,330),1.6) + 0.06*(noise(@x,@y,60,2)-0.5))' } },
      skyYT: { type: 'tint', in: { geo: 'frame', field: 'skyY' }, params: { ink: 'yellow', cell: '$cellYellow', angle: '$angleYellow*PI/180' } },
      skyP: { type: 'field', params: { expr: 'clamp(0.85 - 0.95*lin(@x,@y,0,0,0,460) - 0.4*radial(@x,@y,720,590,450) + 0.14*(noise(@x+100,@y,80,3)-0.5))' } },
      skyPT: { type: 'tint', in: { geo: 'frame', field: 'skyP' }, params: { ink: 'pink', cell: '$cellPink', angle: '$anglePink*PI/180' } },
      skyB: { type: 'field', params: { expr: 'clamp(0.55 - 0.7*lin(@x,@y,0,0,0,380) + 0.12*(noise(@x,@y,70,4)-0.5))' } },
      skyBT: { type: 'tint', in: { geo: 'frame', field: 'skyB' }, params: { ink: 'blue', cell: '$cellBlue', angle: '$angleBlue*PI/180' } },
      // sun: paper disc with light ripples around it
      sun: { type: 'circle', params: { x: 720, y: 590, r: 148, n: 80 } },
      sunC: { type: 'fill', in: { geo: 'sun' }, params: { ink: 'all', mode: 'cut' } },
      ripples: { type: 'copy', params: { n: 3 }, template: { nodes: { c: { type: 'circle', params: { x: 720, y: 590, r: '190 + @i*55 + 6*sin(t*1.2+@i)', n: 120 } } }, output: 'c' } },
      ripplesH: { type: 'hand', in: { geo: 'ripples' }, params: { step: 8, wobble: 3, wave: 140, jitter: 0.4, press: 0.7, taper: 0, overshoot: 0 } },
      ripplesW: { type: 'wrangle', in: { geo: 'ripplesH' }, params: { w: '@pw*1.2*max(0, noise(@v*1200,@i*9,100,11)-0.35)*2' } },
      ripplesC: { type: 'stroke', in: { geo: 'ripplesW' }, params: { ink: 'all', mode: 'cut', tone: 1 } },
      // hills: purple far range, darker mid range, green near hills with tree clumps
      h1: { type: 'ridge', params: { y: 610, bottom: 760, amp: 65, scale: 420, seed: 3, sharp: 0, blue: 0.35, pink: 0.6, fade: 0.4, cell: 7, detail: 0.3, rim: 3 } },
      h2: { type: 'ridge', params: { y: 700, bottom: 860, amp: 75, scale: 300, seed: 9, sharp: 0, blue: 0.55, pink: 0.62, fade: 0.3, cell: 7, detail: 0.35, rim: 2.5 } },
      g1base: { type: 'line', params: { x0: -20, y0: 790, x1: 1100, y1: 790, n: 200 } },
      g1top: { type: 'wrangle', in: { geo: 'g1base' }, params: { y: '@y - 60*noise(@x,0,330,14) - 15*noise(@x,3,90,15) + 40*lin(@x,@y,0,0,1080,0)' } },
      g1foot: { type: 'polygon', params: { pts: '1100 1100 -20 1100', closed: 0 } },
      g1: { type: 'join', in: { list: ['g1top', 'g1foot'] }, params: { close: 1 } },
      g1Y: { type: 'fill', in: { geo: 'g1' }, params: { ink: 'yellow', mode: 'solid' } },
      g1F: { type: 'field', params: { expr: 'clamp(0.35 + 0.5*lin(@x,@y,0,760,0,1080) + 0.25*(noise(@x,@y,50,16)-0.5))' } },
      g1B: { type: 'tint', in: { geo: 'g1', field: 'g1F' }, params: { ink: 'blue', cell: '$cellBlue', angle: '$angleBlue*PI/180' } },
      g1rim: { type: 'hand', in: { geo: 'g1top' }, params: { step: 5, wobble: 1.2, wave: 40, jitter: 0.4, press: 0.5, taper: 0, overshoot: 0 } },
      g1rimC: { type: 'stroke', in: { geo: 'g1rim' }, params: { ink: 'all', mode: 'cut', w: 3 } },
      treeBox: { type: 'polygon', params: { pts: '0 800 200 780 420 820 700 850 1080 800 1080 1080 0 1080' } },
      treePts: { type: 'scatter', in: { geo: 'treeBox' }, params: { count: 90 } },
      trees: { type: 'copy', in: { points: 'treePts' }, params: { orient: 0, scale: '0.6+0.9*rand(2)' }, template: { nodes: {
        a: { type: 'circle', params: { x: -14, y: 4, r: 17, n: 16 } }, b: { type: 'circle', params: { x: 10, y: -4, r: 22, n: 16 } }, c: { type: 'circle', params: { x: 4, y: 14, r: 15, n: 16 } },
        all: { type: 'merge', in: { list: ['a', 'b', 'c'] } } }, output: 'all' } },
      treesC: { type: 'crop', in: { marks: ['treesB'], geo: 'g1' } },
      treesB: { type: 'fill', in: { geo: 'trees' }, params: { ink: 'blue', mode: 'add', tone: 0.75 } },
      fore: { type: 'polygon', params: { pts: '600 1100 700 1030 760 1040 820 990 900 1000 960 960 1040 980 1100 950 1100 1100' } },
      foreH: { type: 'hand', in: { geo: 'fore' }, params: { step: 6, wobble: 6, wave: 40, jitter: 1, press: 0, taper: 0, overshoot: 0 } },
      foreY: { type: 'fill', in: { geo: 'foreH' }, params: { ink: 'yellow', mode: 'solid' } },
      foreB: { type: 'fill', in: { geo: 'foreH' }, params: { ink: 'blue', mode: 'add', tone: 0.95 } },
      // balloons, far to near
      bTiny: { type: 'balloonsBalloon', params: { x: 140, y: 30, r: 38, gores: 8, ncol: 2, inkA: 'pink', mixA: 'none', inkB: 'yellow', mixB: 'blue', shade: 0.3, sway: 3, seed: 6 } },
      bBlue: { type: 'balloonsBalloon', params: { x: 632, y: 100, r: 62, gores: 6, ncol: 2, inkA: 'blue', mixA: 'none', inkB: 'blue', mixB: 'none', shade: 0.4, band: 1, bandY: 0.1, zig: 1, zigInk: 'all', zigY: -0.35, sway: 3, seed: 2 } },
      bGreen: { type: 'balloonsBalloon', params: { x: 862, y: 300, r: 98, gores: 9, ncol: 3, inkA: 'yellow', mixA: 'blue', inkB: 'pink', mixB: 'yellow', inkC: 'yellow', mixC: 'none', shade: 0.55, sway: 4, seed: 3 } },
      bSmallG: { type: 'balloonsBalloon', params: { x: 985, y: 640, r: 58, gores: 1, ncol: 1, inkA: 'yellow', mixA: 'blue', shade: 0.4, zig: 1, zigInk: 'pink', zigY: -0.2, sway: 3, seed: 4 } },
      bPink: { type: 'balloonsBalloon', params: { x: 305, y: 340, r: 168, gores: 8, ncol: 1, inkA: 'pink', mixA: 'none', shade: 0.9, band: 1, bandY: 0.12, zig: 1, zigInk: 'yellow', zigY: -0.32, sway: 5, seed: 1 } },
      bSmallP: { type: 'balloonsBalloon', params: { x: 705, y: 800, r: 40, gores: 6, ncol: 2, inkA: 'pink', mixA: 'none', inkB: 'all', mixB: 'none', shade: 0.3, sway: 2, seed: 5 } },
      marks: { type: 'merge', in: { list: ['skyYT', 'skyPT', 'skyBT', 'sunC', 'ripplesC', 'bTiny', 'bBlue', 'bGreen', 'h1', 'h2', 'bSmallG', 'g1Y', 'g1B', 'g1rimC', 'treesC', 'foreY', 'foreB', 'bPink', 'bSmallP'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
