// bats: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'bats',
  about: 'a flock of bats over a sunset canyon',
  seed: 13,
  transition: null,
  graph: {
    let: { cellBlue: 7, cellPink: 7, cellYellow: 7.5, angleBlue: 15, anglePink: 45, angleYellow: 0, d: 'lin(@x,@y,0,0,1080,1080)' },
    nodes: {
      // sky: purple top-left, pink middle, orange then yellow at the lower right. All halftone.
      box: { type: 'rect', params: { x: 0, y: 0, w: 1080, h: 1080 } },
      fSkyB: { type: 'field', params: { expr: 'clamp(1.0 - 2.4*lin(@x,@y,0,0,1080,1080) + 0.15*(noise(@x,@y,120,3)-0.5))' } },
      skyB: { type: 'tint', in: { geo: 'box', field: 'fSkyB' }, params: { ink: 'blue', cell: 7, angle: 0.26 } },
      fSkyP: { type: 'field', params: { expr: 'clamp(1.0 - 0.9*pow(lin(@x,@y,0,0,1080,1080),2) + 0.15*(noise(@x+300,@y,90,4)-0.5) - 0.35*radial(@x,@y,840,780,320))' } },
      skyP: { type: 'tint', in: { geo: 'box', field: 'fSkyP' }, params: { ink: 'pink', cell: 7, angle: 0.79 } },
      fSkyY: { type: 'field', params: { expr: 'clamp(-0.5 + 2.0*pow(lin(@x,@y,0,0,1080,1080),1.5) + 0.6*radial(@x,@y,840,780,420) + 0.1*(noise(@x,@y+500,80,5)-0.5))' } },
      skyY: { type: 'tint', in: { geo: 'box', field: 'fSkyY' }, params: { ink: 'yellow', cell: 8, angle: 0 } },
      // sea band, lower right, with a wavy top
      seaTop: { type: 'wave', params: { x0: 560, x1: 1100, y: 850, bumps: 5, amp: 14, n: 60, abs: 0 } },
      seaFoot: { type: 'polygon', params: { pts: '1100 1100 560 1100', closed: 0 } },
      sea: { type: 'join', in: { list: ['seaTop', 'seaFoot'] }, params: { close: 1 } },
      seaY: { type: 'fill', in: { geo: 'sea' }, params: { ink: 'yellow', mode: 'cut' } },
      fSeaB: { type: 'field', params: { expr: 'clamp(0.95 + 0.2*(noise(@x,@y,60,6)-0.5))' } },
      seaB: { type: 'tint', in: { geo: 'sea', field: 'fSeaB' }, params: { ink: 'blue', cell: 7, angle: 0.26 } },
      fSeaP: { type: 'field', params: { expr: 'clamp(0.7 + 0.3*(noise(@x+100,@y,50,7)-0.5))' } },
      seaP: { type: 'tint', in: { geo: 'sea', field: 'fSeaP' }, params: { ink: 'pink', cell: 7, angle: 0.79 } },
      cliff: { type: 'batCliff' },
      mesa: { type: 'batMesa' },
      // bats: the stream from the cliff top to the upper right, a row along the top, three big ones
      stream: { type: 'polygon', params: { pts: '547 760 1067 180 933 60 413 640' } },
      swarm: { type: 'batFlock', in: { geo: 'stream' }, params: { count: 42, size: 33, vary: 0.35, heading: -0.84, drift: 18, seed: 2 } },
      streamLow: { type: 'polygon', params: { pts: '547 760 807 470 673 350 413 640' } },
      swarmLow: { type: 'batFlock', in: { geo: 'streamLow' }, params: { count: 30, size: 30, vary: 0.35, heading: -0.84, drift: 18, seed: 8 } },
      topRow: { type: 'polygon', params: { pts: '500 30 1080 30 1080 90 500 90' } },
      topBats: { type: 'batFlock', in: { geo: 'topRow' }, params: { count: 12, size: 40, vary: 0.4, heading: -0.2, drift: 12, seed: 5 } },
      big1: { type: 'batSilhouette', params: { x: 335, y: 175, w: 190, rot: 0.1, flap: '1+0.2*sin(t*5)', seed: 11 } },
      big2: { type: 'batSilhouette', params: { x: '845 + 4*sin(t*1.3)', y: '385 + 5*sin(t*1.7)', w: 270, rot: -0.15, flap: '1+0.2*sin(t*4.5+1)', seed: 12 } },
      big3: { type: 'batSilhouette', params: { x: 965, y: 660, w: 175, rot: 0.05, flap: '1+0.25*sin(t*5.5+2)', seed: 13 } },
      bigs: { type: 'merge', in: { list: ['big1', 'big2', 'big3'] } },
      bigB: { type: 'fill', in: { geo: 'bigs' }, params: { ink: 'blue', mode: 'add', tone: 1 } },
      bigP: { type: 'fill', in: { geo: 'bigs' }, params: { ink: 'pink', mode: 'add', tone: 0.8 } },
      bigY: { type: 'fill', in: { geo: 'bigs' }, params: { ink: 'yellow', mode: 'add', tone: 1 } },
      // sonar above three bats
      s1: { type: 'batSonar', params: { x: 320, y: 120, r0: 45, gap: 27, count: 4, w: 6.5, a0: -160, a1: -20, seed: 1 } },
      s2: { type: 'batSonar', params: { x: 900, y: 280, r0: 55, gap: 34, count: 4, w: 7, a0: -165, a1: -20, seed: 2 } },
      s3: { type: 'batSonar', params: { x: 955, y: 610, r0: 38, gap: 26, count: 4, w: 6, a0: -160, a1: -25, seed: 3 } },
      marks: { type: 'merge', in: { list: ['skyB', 'skyP', 'skyY', 'seaY', 'seaB', 'seaP', 'cliff', 'mesa', 'swarm', 'swarmLow', 'topBats', 'bigB', 'bigP', 'bigY', 's1', 's2', 's3'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
