// bell: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'bell',
  about: 'a temple bell ringing over the sea at sunset',
  seed: 5,
  transition: null,
  graph: {
    let: { cellBlue: 5.6, cellPink: 5.2, cellYellow: 6.2, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      sky: { type: 'sky', params: { y: 0, h: 850, blueTop: 0.12, blueBottom: 0.0, pinkTop: 1.0, pinkBottom: 0.55, yellowTop: 0.35, yellowBottom: 1.0, mottle: 0.15, seed: 6 } },
      sound: { type: 'bellRings', params: { x: '420 + 6*sin(t*0.8)', y: 520, r0: 150, gap: 62, count: 14, a0: -180, a1: 180, spread: 0, ink: 'yellow', mode: 'solid', w: 3.5, wobble: 2.5, taper: 0, drift: 40, seed: 2 } },
      // the eave: dark beams across the top
      eave: { type: 'polygon', params: { pts: '-10 -10 1100 -10 1100 22 -10 22' } },
      eaveF: { type: 'fill', in: { geo: 'eave' }, params: { ink: 'all', mode: 'add' } },
      eaveLines: { type: 'copy', params: { n: 3 }, template: { nodes: { l: { type: 'line', params: { x0: -10, y0: '30 + @i*14', x1: 1100, y1: '30 + @i*14', n: 60 } }, w: { type: 'wrangle', in: { geo: 'l' }, params: { w: '2 + 2*noise(@x,@i*20,120,4)' } } }, output: 'w' } },
      eaveH: { type: 'hand', in: { geo: 'eaveLines' }, params: { step: 7, wobble: 1, wave: 150, jitter: 0.4, press: 0.4, taper: 0, overshoot: 0 } },
      eaveS: { type: 'stroke', in: { geo: 'eaveH' }, params: { ink: 'all', mode: 'add' } },
      // pine branch top left
      branch: { type: 'polygon', params: { pts: '-10 110 60 150 130 180 200 200', closed: 0 } },
      branchW: { type: 'wrangle', in: { geo: 'branch' }, params: { y: '@y + 3*sin(t*1.2)*@v', w: '7 - 4*@v' } },
      branchH: { type: 'hand', in: { geo: 'branchW' }, params: { step: 6, wobble: 1.5, wave: 80, jitter: 0.4, press: 0.4, taper: 0.2, overshoot: 0 } },
      branchS: { type: 'stroke', in: { geo: 'branchH' }, params: { ink: 'all', mode: 'add' } },
      needlePts: { type: 'polygon', params: { pts: '30 100 90 130 150 165 200 200 110 220', closed: 0 } },
      reeds: { type: 'polygon', params: { pts: '790 90 830 170 850 260 840 330', closed: 0 } },
      reeds2: { type: 'polygon', params: { pts: '830 80 880 160 900 250', closed: 0 } },
      reedsAll: { type: 'merge', in: { list: ['reeds', 'reeds2'] } },
      reedsW: { type: 'wrangle', in: { geo: 'reedsAll' }, params: { x: '@x + 4*sin(t*1.3)*@v', w: '3 - 2*@v' } },
      reedsH: { type: 'hand', in: { geo: 'reedsW' }, params: { step: 6, wobble: 1.5, wave: 80, jitter: 0.4, press: 0.4, taper: 0.3, overshoot: 0 } },
      reedsS: { type: 'stroke', in: { geo: 'reedsH' }, params: { ink: 'blue', mode: 'add' } },
      dashPts: { type: 'polygon', params: { pts: '700 150 760 260 800 470 690 420 980 300 1000 520 60 520 90 450', closed: 0 } },
      dashes: { type: 'copy', in: { points: 'dashPts' }, params: { orient: 0 }, template: { nodes: { l: { type: 'line', params: { x0: '-30-60*rand(1)', y0: 0, x1: '30+60*rand(2)', y1: 0, n: 8 } }, w: { type: 'wrangle', in: { geo: 'l' }, params: { w: '4*sin(@v*PI)' } } }, output: 'w' } },
      dashesS: { type: 'stroke', in: { geo: 'dashes' }, params: { ink: 'yellow', mode: 'solid' } },
      needles: { type: 'copy', in: { points: 'needlePts' }, params: { orient: 0, rot: '(rand(1)-0.5)*0.6 + 0.02*sin(t*1.2+@i)', scale: '0.8 + 0.5*rand(2)' }, template: { nodes: {
        r: { type: 'rays', params: { x: 0, y: 0, a0: -20, a1: 200, count: 20, r0: 4, r1: 78 } },
        w: { type: 'wrangle', in: { geo: 'r' }, params: { x: '@x*(0.8+0.4*rand(3))', y: '@y*(0.8+0.4*rand(3))', w: '4 - 3*@v' } } }, output: 'w' } },
      needlesH: { type: 'hand', in: { geo: 'needles' }, params: { step: 5, wobble: 1, wave: 40, jitter: 0.3, press: 0.3, taper: 0.2, overshoot: 0 } },
      needlesB: { type: 'stroke', in: { geo: 'needlesH' }, params: { ink: 'blue', mode: 'solid' } },
      needlesY: { type: 'stroke', in: { geo: 'needlesH' }, params: { ink: 'yellow', mode: 'add' } },
      // a pole and a log on the right
      pole: { type: 'polygon', params: { pts: '852 -10 876 -10 880 700 856 700' } },
      poleF: { type: 'fill', in: { geo: 'pole' }, params: { ink: 'all', mode: 'add' } },
      poleHi: { type: 'polygon', params: { pts: '870 -10 870 700', closed: 0 } },
      poleHiS: { type: 'stroke', in: { geo: 'poleHi' }, params: { ink: 'blue', mode: 'cut', w: 3 } },
      log: { type: 'polygon', params: { pts: '680 600 1100 592 1100 706 680 700' } },
      logEnd: { type: 'ellipse', params: { x: 682, y: 650, rx: 22, ry: 52, n: 40 } },
      logAll: { type: 'merge', in: { list: ['log', 'logEnd'] } },
      logF: { type: 'fill', in: { geo: 'logAll' }, params: { ink: 'all', mode: 'add' } },
      logLines: { type: 'copy', params: { n: 5 }, template: { nodes: { l: { type: 'line', params: { x0: 700, y0: '612 + @i*19', x1: 1100, y1: '606 + @i*19', n: 40 } }, w: { type: 'wrangle', in: { geo: 'l' }, params: { w: '1.5 + 2.5*noise(@x,@i*30,80,7)' } } }, output: 'w' } },
      logLinesH: { type: 'hand', in: { geo: 'logLines' }, params: { step: 6, wobble: 1, wave: 100, jitter: 0.4, press: 0.4, taper: 0.2, overshoot: 0 } },
      logLinesS: { type: 'stroke', in: { geo: 'logLinesH' }, params: { ink: 'blue', mode: 'cut' } },
      logEndS: { type: 'stroke', in: { geo: 'logEnd' }, params: { ink: 'blue', mode: 'cut', w: 2.5 } },
      logRing: { type: 'ellipse', params: { x: 682, y: 650, rx: 10, ry: 26, n: 30 } },
      logRingS: { type: 'stroke', in: { geo: 'logRing' }, params: { ink: 'blue', mode: 'cut', w: 2 } },
      // sea: purple with paper speckle and cut ripples around the bell
      glow: { type: 'ellipse', params: { x: 840, y: 790, rx: 120, ry: 60, n: 50 } },
      glowY: { type: 'fill', in: { geo: 'glow' }, params: { ink: 'yellow', mode: 'solid' } },
      sea: { type: 'bellWaves', params: { y: 830, bottom: 1100, bumps: 7, amp: 60, rows: 0, blue: 1, pink: 1, foam: 0, speckle: 5200, speed: 0.6, seed: 3 } },
      ripples: { type: 'bellRings', params: { x: 420, y: 560, r0: 300, gap: 75, count: 9, a0: 10, a1: 170, spread: 10, ink: 'all', mode: 'cut', w: 5, wobble: 3, taper: 0.3, drift: 30, seed: 4 } },
      seaBox: { type: 'rect', params: { x: -10, y: 790, w: 1100, h: 320 } },
      ripplesC: { type: 'crop', in: { marks: 'ripples', geo: 'seaBox' } },
      big: { type: 'bell', params: { x: 420, y: 250, rot: '0.008*sin(t*0.8)' } },
      marks: { type: 'merge', in: { list: ['sky', 'sound', 'eaveF', 'eaveS', 'branchS', 'needlesB', 'needlesY', 'reedsS', 'dashesS', 'poleF', 'poleHiS', 'logF', 'logLinesS', 'logEndS', 'logRingS', 'glowY', 'sea', 'ripplesC', 'big'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
