// bicycle: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'bicycle',
  about: 'a blue bicycle with a flower basket under a blossoming tree, petals falling',
  seed: 8,
  transition: null,
  graph: {
    let: { cellBlue: 6, cellPink: 6, cellYellow: 6.5, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      // yellow page with a red speckle, denser at the top
      page: { type: 'rect', params: { x: -10, y: -10, w: 1100, h: 1100 } },
      pageY: { type: 'fill', in: { geo: 'page' }, params: { ink: 'yellow', mode: 'solid' } },
      speckPts: { type: 'scatter', in: { geo: 'page' }, params: { count: 2600 } },
      speck: { type: 'dots', in: { geo: 'speckPts' }, params: { ink: 'pink', mode: 'add', tone: 0.9, r: '(0.6+1.4*rand(1))*(rand(2) < 1.1-@y/900 ? 1 : 0)' } },
      // leaves: green lens shapes all over the tree
      leafBox: { type: 'polygon', params: { pts: '-10 -10 1090 -10 1090 620 700 520 380 640 -10 900' } },
      leafPts: { type: 'scatter', in: { geo: 'leafBox' }, params: { count: 150 } },
      leaves: { type: 'copy', in: { points: 'leafPts' }, params: { orient: 0, rot: 'rand(1)*TAU + 0.05*sin(t*1.5+rand(4)*6)', scale: '0.85+0.8*rand(2)' }, template: { nodes: {
        l: { type: 'lens', params: { len: 17, wid: 12, n: 8 } } }, output: 'l' } },
      leavesF: { type: 'field', params: { expr: '0.55 + 0.15*(noise(@x,@y,30,4)-0.5)' } },
      leavesB: { type: 'tint', in: { geo: 'leaves', field: 'leavesF' }, params: { ink: 'blue', cell: 5, angle: 0.5 } },
      leavesE: { type: 'stroke', in: { geo: 'leaves' }, params: { ink: 'blue', mode: 'add', w: 1.2, tone: 0.8 } },
      // blossom clusters: pink dots in clumps, a few paper cuts inside
      clusterPts: { type: 'polygon', params: { pts: '60 60 420 40 520 110 640 40 760 80 900 30 1040 100 180 220 300 320 120 400 40 560 160 640 60 760 980 320 1050 480', closed: 0 } },
      blossom: { type: 'copy', in: { points: 'clusterPts' }, params: { orient: 0 }, template: { nodes: {
        c: { type: 'circle', params: { x: 0, y: 0, r: '55+40*rand(1)', n: 12 } },
        p: { type: 'scatter', in: { geo: 'c' }, params: { count: '40+floor(rand(2)*20)' } } }, output: 'p' } },
      blossomP: { type: 'dots', in: { geo: 'blossom' }, params: { ink: 'pink', mode: 'solid', tone: 0.9, r: '4+6*rand(1)' } },
      blossomP2: { type: 'dots', in: { geo: 'blossom' }, params: { ink: 'pink', mode: 'add', r: '(2+3*rand(3))*(rand(4)<0.5)' } },
      blossomW: { type: 'dots', in: { geo: 'blossom' }, params: { ink: 'all', mode: 'cut', r: '(1.2+1.8*rand(2))*(rand(5)<0.45)' } },
      // petals drifting down
      petalPts: { type: 'scatter', in: { geo: 'page' }, params: { count: 40 } },
      petals: { type: 'copy', in: { points: 'petalPts' }, params: { orient: 0, x: '12*sin(t*1.2+rand(1)*6)', y: '(t*30 + rand(2)*1080) % 1100 - @py', rot: 'rand(3)*TAU + t*0.8' }, template: { nodes: {
        l: { type: 'lens', params: { len: 7, wid: 7, n: 8 } } }, output: 'l' } },
      petalsP: { type: 'fill', in: { geo: 'petals' }, params: { ink: 'pink', mode: 'solid', tone: 0.95 } },
      // ground: an orange kerb, pale tiles, the bicycle's shadow
      kerb: { type: 'polygon', params: { pts: '-10 900 1090 896 1090 940 -10 944' } },
      kerbF: { type: 'field', params: { expr: '0.55 + 0.2*(noise(@x,@y,40,7)-0.5)' } },
      kerbP: { type: 'tint', in: { geo: 'kerb', field: 'kerbF' }, params: { ink: 'pink', cell: '$cellPink', angle: 0.8 } },
      kerbL: { type: 'polygon', params: { pts: '-10 900 1090 896', closed: 0 } },
      kerbLS: { type: 'stroke', in: { geo: 'kerbL' }, params: { ink: 'blue', mode: 'add', w: 3, tone: 0.5 } },
      tiles: { type: 'polygon', params: { pts: '-10 944 1090 940 1090 1090 -10 1090' } },
      tilesW: { type: 'fill', in: { geo: 'tiles' }, params: { ink: 'all', mode: 'cut' } },
      tilesF: { type: 'field', params: { expr: '0.16 + 0.12*(noise(@x,@y,50,8)-0.5)' } },
      tilesB: { type: 'tint', in: { geo: 'tiles', field: 'tilesF' }, params: { ink: 'blue', cell: '$cellBlue', angle: 0.26 } },
      tileL1: { type: 'polygon', params: { pts: '-10 1012 1090 1006', closed: 0 } },
      tileL2: { type: 'copy', params: { n: 12, x: '-10+@i*95' }, template: { nodes: { l: { type: 'line', params: { x0: 0, y0: 944, x1: 8, y1: 1090, n: 2 } } }, output: 'l' } },
      tileL: { type: 'merge', in: { list: ['tileL1', 'tileL2'] } },
      tileLH: { type: 'hand', in: { geo: 'tileL' }, params: { step: 8, wobble: 1, wave: 100, jitter: 0.3, press: 0.4, taper: 0, overshoot: 0 } },
      tileLS: { type: 'stroke', in: { geo: 'tileLH' }, params: { ink: 'blue', mode: 'add', tone: 0.55 } },
      shadow: { type: 'polygon', params: { pts: '190 972 300 958 520 962 700 955 930 962 960 985 900 1008 640 1004 420 1010 220 1002' } },
      shadowH: { type: 'hand', in: { geo: 'shadow' }, params: { step: 8, wobble: 4, wave: 60, jitter: 1, press: 0, taper: 0, overshoot: 0 } },
      shadowF: { type: 'field', params: { expr: '0.5 + 0.2*(noise(@x,@y,30,9)-0.5)' } },
      shadowPF: { type: 'field', params: { expr: '0.28 + 0.15*(noise(@x,@y,30,10)-0.5)' } },
      shadowB: { type: 'tint', in: { geo: 'shadowH', field: 'shadowF' }, params: { ink: 'blue', cell: '$cellBlue', angle: 0.26 } },
      shadowP: { type: 'tint', in: { geo: 'shadowH', field: 'shadowPF' }, params: { ink: 'pink', cell: '$cellPink', angle: 0.8 } },
      // the bicycle
      rear: { type: 'bicycleWheel', params: { x: 290, y: 775, r: 172, spokes: 30, tyre: 10, dark: 0.55 } },
      front: { type: 'bicycleWheel', params: { x: 815, y: 778, r: 166, spokes: 30, tyre: 10, dark: 0.55 } },
      frame: { type: 'polygon', params: { pts: '525 800 470 500 738 470 762 545 525 800 290 775 470 500 290 775 525 800', closed: 0 } },
      fork: { type: 'polygon', params: { pts: '738 470 762 545 815 778', closed: 0 } },
      headtube: { type: 'polygon', params: { pts: '722 440 762 545', closed: 0 } },
      stem: { type: 'polygon', params: { pts: '722 440 690 440 640 452', closed: 0 } },
      seatpost: { type: 'polygon', params: { pts: '470 500 462 462', closed: 0 } },
      crank: { type: 'polygon', params: { pts: '525 800 580 862', closed: 0 } },
      chain: { type: 'polygon', params: { pts: '525 842 290 787', closed: 0 } },
      chain2: { type: 'polygon', params: { pts: '525 758 290 763', closed: 0 } },
      tubes: { type: 'merge', in: { list: ['frame', 'fork', 'headtube', 'stem', 'seatpost', 'crank'] } },
      tubesH: { type: 'hand', in: { geo: 'tubes' }, params: { step: 8, wobble: 1.2, wave: 120, jitter: 0.4, press: 0.3, taper: 0, overshoot: 2 } },
      tubesW: { type: 'wrangle', in: { geo: 'tubesH' }, params: { w: '@pw*6.5' } },
      tubesS: { type: 'stroke', in: { geo: 'tubesW' }, params: { ink: 'blue', mode: 'solid' } },
      chains: { type: 'merge', in: { list: ['chain', 'chain2'] } },
      chainsH: { type: 'hand', in: { geo: 'chains' }, params: { step: 8, wobble: 1, wave: 120, jitter: 0.4, press: 0.3, taper: 0, overshoot: 0 } },
      chainsW: { type: 'wrangle', in: { geo: 'chainsH' }, params: { w: '@pw*1.6' } },
      chainsS: { type: 'stroke', in: { geo: 'chainsW' }, params: { ink: 'blue', mode: 'solid' } },
      ring: { type: 'circle', params: { x: 525, y: 800, r: 44, n: 48 } },
      ringH: { type: 'hand', in: { geo: 'ring' }, params: { step: 7, wobble: 1, wave: 100, jitter: 0.3, press: 0.3, taper: 0, overshoot: 0 } },
      ringW: { type: 'wrangle', in: { geo: 'ringH' }, params: { w: '@pw*3.5' } },
      ringS: { type: 'stroke', in: { geo: 'ringW' }, params: { ink: 'blue', mode: 'solid' } },
      pedal: { type: 'polygon', params: { pts: '566 862 596 862', closed: 0 } },
      pedalS: { type: 'stroke', in: { geo: 'pedal' }, params: { ink: 'blue', mode: 'solid', w: 7 } },
      stand: { type: 'polygon', params: { pts: '560 812 600 888', closed: 0 } },
      standS: { type: 'stroke', in: { geo: 'stand' }, params: { ink: 'blue', mode: 'solid', w: 4 } },
      standFoot: { type: 'ellipse', params: { x: 602, y: 890, rx: 14, ry: 5 } },
      standFootS: { type: 'fill', in: { geo: 'standFoot' }, params: { ink: 'blue', mode: 'solid' } },
      saddle: { type: 'ellipse', params: { x: 458, y: 452, rx: 48, ry: 14, rot: -0.06 } },
      saddleB: { type: 'fill', in: { geo: 'saddle' }, params: { ink: 'blue', mode: 'solid' } },
      saddleP: { type: 'fill', in: { geo: 'saddle' }, params: { ink: 'pink', mode: 'add', tone: 0.9 } },
      grip: { type: 'ellipse', params: { x: 640, y: 440, rx: 20, ry: 9, rot: 0.2 } },
      gripB: { type: 'fill', in: { geo: 'grip' }, params: { ink: 'blue', mode: 'solid' } },
      gripP: { type: 'fill', in: { geo: 'grip' }, params: { ink: 'pink', mode: 'add', tone: 0.9 } },
      bar: { type: 'ellipse', params: { x: 722, y: 470, rx: 40, ry: 22, a0: 180, a1: 300, n: 16 } },
      barS: { type: 'stroke', in: { geo: 'bar' }, params: { ink: 'blue', mode: 'solid', w: 6 } },
      // the bell and its sound
      bell: { type: 'ellipse', params: { x: 716, y: 408, rx: 34, ry: 30, a0: 180, a1: 360, n: 24 } },
      bellW: { type: 'fill', in: { geo: 'bell' }, params: { ink: 'all', mode: 'cut' } },
      bellF: { type: 'field', params: { expr: '0.45' } },
      bellB: { type: 'tint', in: { geo: 'bell', field: 'bellF' }, params: { ink: 'blue', cell: 5, angle: 0.3 } },
      bellS: { type: 'stroke', in: { geo: 'bell' }, params: { ink: 'blue', mode: 'solid', w: 3 } },
      bellBase: { type: 'polygon', params: { pts: '690 410 742 410', closed: 0 } },
      bellBaseS: { type: 'stroke', in: { geo: 'bellBase' }, params: { ink: 'blue', mode: 'solid', w: 4 } },
      ding: { type: 'copy', params: { n: 3 }, template: { nodes: {
        a: { type: 'ellipse', params: { x: 716, y: 390, rx: '70+@i*48+3*sin(t*5+@i)', ry: '70+@i*48+3*sin(t*5+@i)', a0: '-95-@i*4', a1: '-25-@i*3', n: 16 } } }, output: 'a' } },
      dingH: { type: 'hand', in: { geo: 'ding' }, params: { step: 6, wobble: 1.2, wave: 60, jitter: 0.4, press: 0.4, taper: 0.5, overshoot: 0 } },
      dingW: { type: 'wrangle', in: { geo: 'dingH' }, params: { w: '@pw*3' } },
      dingS: { type: 'stroke', in: { geo: 'dingW' }, params: { ink: 'blue', mode: 'solid' } },
      // the basket of flowers on the front rack
      basket: { type: 'polygon', params: { pts: '838 560 992 566 980 680 848 676' } },
      basketP: { type: 'fill', in: { geo: 'basket' }, params: { ink: 'pink', mode: 'solid' } },
      basketY: { type: 'fill', in: { geo: 'basket' }, params: { ink: 'yellow', mode: 'add', tone: 0.9 } },
      weaveH: { type: 'copy', params: { n: 7, y: '575+@i*16' }, template: { nodes: { l: { type: 'line', params: { x0: 842, y0: 0, x1: 988, y1: 2, n: 2 } } }, output: 'l' } },
      weaveV: { type: 'copy', params: { n: 8, x: '850+@i*20' }, template: { nodes: { l: { type: 'line', params: { x0: 0, y0: 562, x1: -2, y1: 678, n: 2 } } }, output: 'l' } },
      weave: { type: 'merge', in: { list: ['weaveH', 'weaveV'] } },
      weaveS: { type: 'stroke', in: { geo: 'weave' }, params: { ink: 'blue', mode: 'add', w: 2, tone: 0.75 } },
      basketE: { type: 'stroke', in: { geo: 'basket' }, params: { ink: 'blue', mode: 'add', w: 3, tone: 0.9 } },
      rack: { type: 'polygon', params: { pts: '848 676 830 700 815 778', closed: 0 } },
      rackS: { type: 'stroke', in: { geo: 'rack' }, params: { ink: 'blue', mode: 'solid', w: 5 } },
      flowerBox: { type: 'polygon', params: { pts: '850 500 990 505 985 566 838 560' } },
      flowerPts: { type: 'scatter', in: { geo: 'flowerBox' }, params: { count: 40 } },
      flowersP: { type: 'dots', in: { geo: 'flowerPts' }, params: { ink: 'pink', mode: 'solid', tone: 0.9, r: '8+8*rand(1)' } },
      flowersW: { type: 'dots', in: { geo: 'flowerPts' }, params: { ink: 'all', mode: 'cut', r: '(1.5+2*rand(2))*(rand(3)<0.4)' } },
      stalks: { type: 'copy', params: { n: 4, x: '900+@i*25', y: 500 }, template: { nodes: { l: { type: 'line', params: { x0: 0, y0: 0, x1: '10+@i*8', y1: '-60-@i*20', n: 2 } } }, output: 'l' } },
      stalksS: { type: 'stroke', in: { geo: 'stalks' }, params: { ink: 'blue', mode: 'add', w: 2, tone: 0.7 } },
      marks: { type: 'merge', in: { list: ['pageY', 'speck', 'leavesB', 'leavesE', 'blossomP', 'blossomP2', 'blossomW', 'kerbP', 'kerbLS', 'tilesW', 'tilesB', 'tileLS', 'shadowB', 'shadowP',
        'rear', 'front', 'chainsS', 'ringS', 'tubesS', 'pedalS', 'standS', 'standFootS', 'saddleB', 'saddleP', 'barS', 'gripB', 'gripP', 'bellW', 'bellB', 'bellS', 'bellBaseS', 'dingS',
        'stalksS', 'flowersP', 'flowersW', 'basketP', 'basketY', 'weaveS', 'basketE', 'rackS', 'petalsP'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
