// campfire: flames and sparks between logs in a dark forest.
export const scene = {
  name: 'campfire',
  about: 'a campfire in a purple-blue forest at night',
  seed: 23,
  transition: null,
  graph: {
    let: { cellBlue: 7, cellPink: 7, cellYellow: 7.5, angleBlue: 15, anglePink: 45, angleYellow: 0, fx: 520, fy: 800 },
    nodes: {
      // the forest: purple night, teal trunks that warm up near the fire
      night: { type: 'sky', params: { y: 0, h: 1080, blueTop: 1.0, blueBottom: 1.0, pinkTop: 0.8, pinkBottom: 0.55, mottle: 0.25, cell: 7, seed: 2 } },
      trunks: { type: 'copy', params: { n: 12, x: '20 + @i*96 + (rand(1)-0.5)*50', y: 0, scale: 1 }, template: {
        let: { w: '30 + 60*rand(2)', lean: '(rand(3)-0.5)*40', bot: '690 + 160*rand(5)' },
        nodes: { p: { type: 'polygon', params: { pts: '-$w*0.5 -20 $w*0.5 -20 $w*0.6+$lean $bot -$w*0.6+$lean $bot' } },
          r: { type: 'hand', in: { geo: 'p' }, params: { step: 8, wobble: 3, wave: 120, jitter: 1, press: 0, taper: 0, overshoot: 0 } } }, output: 'r' } },
      trunksCut: { type: 'fill', in: { geo: 'trunks' }, params: { ink: 'all', mode: 'cut' } },
      trunkFB: { type: 'field', params: { expr: 'clamp(0.85 - 0.45*radial(@x,@y,$fx,$fy-80,520) + 0.2*(noise(@x,@y,40,4)-0.5))' } },
      trunksB: { type: 'tint', in: { geo: 'trunks', field: 'trunkFB' }, params: { ink: 'blue', cell: 7, angle: 0.26 } },
      trunkFY: { type: 'field', params: { expr: 'clamp(0.35 + 0.65*radial(@x,@y,$fx,$fy-60,560) + 0.2*(noise(@x+90,@y,50,5)-0.5))' } },
      trunksY: { type: 'tint', in: { geo: 'trunks', field: 'trunkFY' }, params: { ink: 'yellow', cell: 7.5, angle: 0 } },
      trunkFP: { type: 'field', params: { expr: 'clamp(0.3 - 0.3*radial(@x,@y,$fx,$fy,600))' } },
      trunksP: { type: 'tint', in: { geo: 'trunks', field: 'trunkFP' }, params: { ink: 'pink', cell: 7, angle: 0.78 } },
      // the ground: a green mound lit by the fire, a yellow halo round the logs
      groundTop: { type: 'wave', params: { x0: -20, x1: 1100, y: 720, bumps: 2, amp: -30, n: 60, abs: 1 } },
      groundFoot: { type: 'polygon', params: { pts: '1100 1100 -20 1100', closed: 0 } },
      ground0: { type: 'join', in: { list: ['groundTop', 'groundFoot'] }, params: { close: 1 } },
      ground: { type: 'hand', in: { geo: 'ground0' }, params: { step: 8, wobble: 6, wave: 90, jitter: 1, press: 0, taper: 0, overshoot: 0 } },
      groundCut: { type: 'fill', in: { geo: 'ground' }, params: { ink: 'all', mode: 'cut' } },
      groundFB: { type: 'field', params: { expr: 'clamp(0.8 - 0.7*radial(@x,@y,$fx,$fy+90,420) + 0.25*(noise(@x,@y,45,6)-0.5))' } },
      groundB: { type: 'tint', in: { geo: 'ground', field: 'groundFB' }, params: { ink: 'blue', cell: 7, angle: 0.26 } },
      groundFY: { type: 'field', params: { expr: 'clamp(0.7 + 0.3*radial(@x,@y,$fx,$fy+90,500) + 0.2*(noise(@x+30,@y+70,60,7)-0.5))' } },
      groundY: { type: 'tint', in: { geo: 'ground', field: 'groundFY' }, params: { ink: 'yellow', cell: 7.5, angle: 0 } },
      groundFP: { type: 'field', params: { expr: 'clamp(0.25*lin(@x,@y,0,800,0,1080) - 0.3*radial(@x,@y,$fx,$fy+90,450))' } },
      groundP: { type: 'tint', in: { geo: 'ground', field: 'groundFP' }, params: { ink: 'pink', cell: 7, angle: 0.78 } },
      halo: { type: 'ellipse', params: { x: '$fx', y: '$fy+95', rx: 330, ry: 105, n: 60 } },
      haloH: { type: 'hand', in: { geo: 'halo' }, params: { step: 8, wobble: 8, wave: 80, jitter: 1, press: 0, taper: 0, overshoot: 0 } },
      haloCut: { type: 'fill', in: { geo: 'haloH' }, params: { ink: 'blue', mode: 'cut' } },
      haloFB: { type: 'field', params: { expr: 'clamp(0.55*(1-radial(@x,@y,$fx,$fy+95,300)))' } },
      haloB: { type: 'tint', in: { geo: 'haloH', field: 'haloFB' }, params: { ink: 'blue', cell: 7, angle: 0.26 } },
      // logs: navy, pink top edges, paper specks; the back pair, then the flames, then the front pair
      logA: { type: 'polygon', params: { pts: '225 858 245 828 505 772 528 792 512 818 250 872' } },
      logB: { type: 'polygon', params: { pts: '330 812 360 790 790 846 838 878 826 905 340 852' } },
      logC: { type: 'polygon', params: { pts: '548 792 566 770 798 842 806 868 780 878 556 816' } },
      logD: { type: 'polygon', params: { pts: '295 892 330 870 690 902 708 930 690 940 318 918' } },
      back: { type: 'merge', in: { list: ['logA', 'logB'] } },
      backH: { type: 'hand', in: { geo: 'back' }, params: { step: 7, wobble: 2, wave: 60, jitter: 0.8, press: 0, taper: 0, overshoot: 0 } },
      backB: { type: 'fill', in: { geo: 'backH' }, params: { ink: 'blue', mode: 'solid' } },
      backP: { type: 'fill', in: { geo: 'backH' }, params: { ink: 'pink', mode: 'add', tone: 0.8 } },
      front: { type: 'merge', in: { list: ['logC', 'logD'] } },
      frontH: { type: 'hand', in: { geo: 'front' }, params: { step: 7, wobble: 2, wave: 60, jitter: 0.8, press: 0, taper: 0, overshoot: 0 } },
      frontB: { type: 'fill', in: { geo: 'frontH' }, params: { ink: 'blue', mode: 'solid' } },
      frontP: { type: 'fill', in: { geo: 'frontH' }, params: { ink: 'pink', mode: 'add', tone: 0.8 } },
      edgeLines: { type: 'copy', params: { n: 4 }, template: { nodes: {
        l: { type: 'line', params: { x0: '@i==0 ? 245 : @i==1 ? 360 : @i==2 ? 566 : 330', y0: '@i==0 ? 828 : @i==1 ? 790 : @i==2 ? 770 : 870', x1: '@i==0 ? 505 : @i==1 ? 790 : @i==2 ? 798 : 690', y1: '@i==0 ? 772 : @i==1 ? 846 : @i==2 ? 842 : 902', n: 12 } } }, output: 'l' } },
      edgesH: { type: 'hand', in: { geo: 'edgeLines' }, params: { step: 6, wobble: 1.5, wave: 70, jitter: 0.5, press: 0.5, taper: 0.3, overshoot: 4 } },
      edgesS: { type: 'stroke', in: { geo: 'edgesH' }, params: { ink: 'pink', mode: 'solid', w: 4 } },
      outlineH: { type: 'hand', in: { geo: 'logsAll' }, params: { step: 7, wobble: 2, wave: 60, jitter: 0.8, press: 0.4, taper: 0, overshoot: 0 } },
      outlineS: { type: 'stroke', in: { geo: 'outlineH' }, params: { ink: 'pink', mode: 'solid', w: 2.5, tone: 0.9 } },
      logsAll: { type: 'merge', in: { list: ['logA', 'logB', 'logC', 'logD'] } },
      speckPts: { type: 'scatter', in: { geo: 'logsAll' }, params: { count: 240 } },
      specks: { type: 'dots', in: { geo: 'speckPts' }, params: { ink: 'all', mode: 'cut', r: '1.8+2.4*rand(1)' } },
      endA: { type: 'ellipse', params: { x: 236, y: 848, rx: 14, ry: 20, rot: 0.3, n: 20 } },
      endB: { type: 'ellipse', params: { x: 830, y: 890, rx: 14, ry: 18, rot: -0.2, n: 20 } },
      ends: { type: 'merge', in: { list: ['endA', 'endB'] } },
      endsY: { type: 'fill', in: { geo: 'ends' }, params: { ink: 'yellow', mode: 'solid', tone: 0.9 } },
      endsS: { type: 'stroke', in: { geo: 'ends' }, params: { ink: 'blue', mode: 'add', w: 3 } },
      stones: { type: 'copy', params: { n: 3, x: '392 + @i*118', y: '936 + (rand(1)-0.5)*14' }, template: { nodes: {
        e: { type: 'ellipse', params: { x: 0, y: 0, rx: '38+10*rand(2)', ry: '24+6*rand(3)', n: 24 } },
        h: { type: 'hand', in: { geo: 'e' }, params: { step: 6, wobble: 3, wave: 40, jitter: 0.8, press: 0, taper: 0, overshoot: 0 } } }, output: 'h' } },
      stonesB: { type: 'fill', in: { geo: 'stones' }, params: { ink: 'blue', mode: 'solid' } },
      stonesP: { type: 'fill', in: { geo: 'stones' }, params: { ink: 'pink', mode: 'add', tone: 0.85 } },
      // flames: orange, yellow, paper core
      outer: { type: 'campfireFlame', params: { x: '$fx', y: '$fy', w: 190, h: 490, ink: 'pink', mode: 'solid', ink2: 'yellow', tone2: 1, sway: 16, speed: 3, wobble: 7, seed: 1 } },
      mid: { type: 'campfireFlame', params: { x: '$fx+6', y: '$fy', w: 150, h: 420, ink: 'pink', mode: 'solid', tone: 0.55, ink2: 'yellow', tone2: 1, sway: 14, speed: 3.4, wobble: 9, seed: 5 } },
      inner: { type: 'campfireFlame', params: { x: '$fx-4', y: '$fy', w: 110, h: 350, ink: 'yellow', mode: 'solid', sway: 12, speed: 3.8, wobble: 10, seed: 9 } },
      core: { type: 'campfireFlame', params: { x: '$fx-4', y: '$fy-10', w: 26, h: 150, ink: 'all', mode: 'cut', sway: 6, speed: 4, wobble: 4, seed: 12 } },
      // sparks drifting up, wrapping every few hundred pixels
      sparkBox: { type: 'polygon', params: { pts: '440 -10 600 -10 640 520 500 520' } },
      sparkPts: { type: 'scatter', in: { geo: 'sparkBox' }, params: { count: 90 } },
      sparkMove: { type: 'wrangle', in: { geo: 'sparkPts' }, params: { x: '@x + 8*sin(t*2+rand(1)*6) + (@y-250)*0.15*(rand(5)-0.5)', y: '-10 + (((@y + 10) - t*(60+60*rand(2))) % 530 + 530) % 530' } },
      sparkDash: { type: 'copy', in: { points: 'sparkMove' }, params: { orient: 0, rot: '-1.3 + (rand(1)-0.5)*0.7' }, template: { nodes: { l: { type: 'line', params: { x0: 0, y0: 0, x1: '4+9*rand(2)', y1: 0, n: 2 } } }, output: 'l' } },
      sparks: { type: 'stroke', in: { geo: 'sparkDash' }, params: { ink: 'yellow', mode: 'solid', w: 3.2 } },
      sparkPinkG: { type: 'transform', in: { geo: 'sparkDash' }, params: { x: 2, y: 1 } },
      sparkPink: { type: 'stroke', in: { geo: 'sparkPinkG' }, params: { ink: 'pink', mode: 'add', w: 1.6, tone: 0.9 } },
      marks: { type: 'merge', in: { list: ['night', 'trunksCut', 'trunksB', 'trunksY', 'trunksP', 'groundCut', 'groundB', 'groundY', 'groundP', 'haloCut', 'haloB', 'backB', 'backP', 'outer', 'mid', 'inner', 'core', 'frontB', 'frontP', 'outlineS', 'edgesS', 'specks', 'endsY', 'endsS', 'stonesB', 'stonesP', 'sparks', 'sparkPink'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
