// city: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'city',
  about: 'a night city: lit towers, a full moon with a halftone halo, a cat in an orange window',
  seed: 31,
  transition: null,
  graph: {
    let: { cellBlue: 5.6, cellPink: 5.2, cellYellow: 6.2, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      frame: { type: 'rect', params: { x: 0, y: 0, w: 1080, h: 1080 } },
      skyB: { type: 'field', params: { expr: 'clamp(0.98 - 0.3*radial(@x,@y,600,285,420) + 0.1*(noise(@x,@y,120,3)-0.5))' } },
      skyBT: { type: 'tint', in: { geo: 'frame', field: 'skyB' }, params: { ink: 'blue', cell: '$cellBlue', angle: '$angleBlue*PI/180' } },
      skyP: { type: 'field', params: { expr: 'clamp(0.7 - 0.35*lin(@x,@y,0,0,0,1080) - 0.45*radial(@x,@y,600,285,400) + 0.2*(noise(@x+200,@y,90,4)-0.5))' } },
      skyPT: { type: 'tint', in: { geo: 'frame', field: 'skyP' }, params: { ink: 'pink', cell: '$cellPink', angle: '$anglePink*PI/180' } },
      starPts: { type: 'scatter', in: { geo: 'frame' }, params: { count: 220 } },
      stars: { type: 'dots', in: { geo: 'starPts' }, params: { ink: 'all', mode: 'cut', r: '(0.6+1.2*rand(1))*(0.8+0.3*sin(t*3+rand(2)*7))' } },
      // moon halo: a radial halftone of paper dots on a grid, yellow inside each
      grid: { type: 'copy', params: { n: 1369 }, template: { nodes: { p: { type: 'point', params: { x: '600 + ((@i%37)-18)*17 + ((floor(@i/37))%2)*8.5', y: '285 + (floor(@i/37)-18)*15' } } }, output: 'p' } },
      haloC: { type: 'dots', in: { geo: 'grid' }, params: { ink: 'all', mode: 'cut', r: 'max(0, 9.5*pow(radial(@x,@y,600,285,360*(1+0.02*sin(t*1.5))),1.3) + 0.6*rand(1) - 0.8)' } },
      haloY: { type: 'dots', in: { geo: 'grid' }, params: { ink: 'yellow', mode: 'add', r: 'max(0, 8*pow(radial(@x,@y,600,285,340),1.3) - 0.8)' } },
      moon: { type: 'circle', params: { x: 600, y: 285, r: 92, n: 80 } },
      moonH: { type: 'hand', in: { geo: 'moon' }, params: { step: 6, wobble: 1.5, wave: 80, jitter: 0.4, press: 0, taper: 0, overshoot: 0 } },
      moonC: { type: 'fill', in: { geo: 'moonH' }, params: { ink: 'all', mode: 'cut' } },
      craterF: { type: 'field', params: { expr: 'clamp(0.5*radial(@x,@y,565,270,28) + 0.5*radial(@x,@y,625,305,24) + 0.4*radial(@x,@y,585,330,18) + 0.4*radial(@x,@y,640,255,14))' } },
      craters: { type: 'tint', in: { geo: 'moon', field: 'craterF' }, params: { ink: 'yellow', cell: 7, angle: 0.3 } },
      // towers
      leftTop: { type: 'cityBuilding', params: { x: 20, y: 45, w: 170, h: 152, cols: 2, rows: 2, winW: 40, winH: 30, lit: 0, floors: 0, seed: 3 } },
      cap: { type: 'rect', params: { x: 40, y: 45, w: 132, h: 36 } },
      capB: { type: 'fill', in: { geo: 'cap' }, params: { ink: 'blue', mode: 'solid' } },
      capP: { type: 'fill', in: { geo: 'cap' }, params: { ink: 'pink', mode: 'add' } },
      capL: { type: 'polygon', params: { pts: '40 81 172 81', closed: 0 } },
      capLS: { type: 'stroke', in: { geo: 'capL' }, params: { ink: 'pink', mode: 'cut', w: 2 } },
      antenna: { type: 'polygon', params: { pts: '315 48 315 195 292 85 338 85 298 120 332 120', closed: 0 } },
      antennaB: { type: 'stroke', in: { geo: 'antenna' }, params: { ink: 'blue', mode: 'solid', w: 5 } },
      antennaP: { type: 'stroke', in: { geo: 'antenna' }, params: { ink: 'pink', mode: 'add', w: 5 } },
      left: { type: 'cityBuilding', params: { x: -30, y: 195, w: 455, h: 900, cols: 7, rows: 10, winW: 42, winH: 42, lit: 0.62, seed: 1 } },
      bigWin: { type: 'rect', params: { x: 232, y: 668, w: 155, h: 122 } },
      bigWinY: { type: 'fill', in: { geo: 'bigWin' }, params: { ink: 'yellow', mode: 'solid' } },
      bigWinF: { type: 'field', params: { expr: '0.45*lin(@x,@y,0,700,0,790)' } },
      bigWinT: { type: 'tint', in: { geo: 'bigWin', field: 'bigWinF' }, params: { ink: 'blue', cell: 5, angle: 0.3 } },
      lamp: { type: 'polygon', params: { pts: '268 668 268 700 292 700 292 668 292 700 315 700 292 712', closed: 0 } },
      lampG: { type: 'polygon', params: { pts: '270 700 314 700 300 720 284 720' } },
      shelf: { type: 'polygon', params: { pts: '330 735 380 735 380 742 330 742 340 715 350 715 350 735 362 725 372 725 372 735', closed: 0 } },
      lampAll: { type: 'merge', in: { list: ['lamp', 'lampG', 'shelf'] } },
      lampS: { type: 'stroke', in: { geo: 'lampAll' }, params: { ink: 'blue', mode: 'add', w: 4 } },
      lampF: { type: 'fill', in: { geo: 'lampG' }, params: { ink: 'blue', mode: 'add' } },
      lampP: { type: 'fill', in: { geo: 'lampG' }, params: { ink: 'pink', mode: 'add' } },
      // rooftop between the towers
      roof: { type: 'rect', params: { x: 430, y: 770, w: 330, h: 320 } },
      roofB: { type: 'fill', in: { geo: 'roof' }, params: { ink: 'blue', mode: 'solid' } },
      roofP: { type: 'fill', in: { geo: 'roof' }, params: { ink: 'pink', mode: 'add' } },
      roofPts: { type: 'scatter', in: { geo: 'roof' }, params: { count: 80 } },
      roofG: { type: 'dots', in: { geo: 'roofPts' }, params: { ink: 'pink', mode: 'cut', r: '0.6+1.2*rand(1)' } },
      tank: { type: 'polygon', params: { pts: '500 645 537 616 575 645 578 700 498 700' } },
      tankLegs: { type: 'polygon', params: { pts: '508 700 503 772 503 738 570 738 570 772 566 700', closed: 0 } },
      tankF: { type: 'fill', in: { geo: 'tank' }, params: { ink: 'blue', mode: 'solid' } },
      tankP: { type: 'fill', in: { geo: 'tank' }, params: { ink: 'pink', mode: 'add' } },
      tankLB: { type: 'stroke', in: { geo: 'tankLegs' }, params: { ink: 'blue', mode: 'solid', w: 5 } },
      tankLP: { type: 'stroke', in: { geo: 'tankLegs' }, params: { ink: 'pink', mode: 'add', w: 5 } },
      hut: { type: 'rect', params: { x: 624, y: 724, w: 68, h: 48 } },
      hutY: { type: 'fill', in: { geo: 'hut' }, params: { ink: 'yellow', mode: 'solid' } },
      hutB: { type: 'stroke', in: { geo: 'hut' }, params: { ink: 'blue', mode: 'solid', w: 6 } },
      hutP: { type: 'stroke', in: { geo: 'hut' }, params: { ink: 'pink', mode: 'add', w: 6 } },
      right: { type: 'cityBuilding', params: { x: 755, y: 470, w: 340, h: 640, cols: 7, rows: 8, winW: 28, winH: 50, lit: 0.6, seed: 2 } },
      setback: { type: 'rect', params: { x: 948, y: 440, w: 150, h: 32 } },
      setbackB: { type: 'fill', in: { geo: 'setback' }, params: { ink: 'blue', mode: 'solid' } },
      setbackP: { type: 'fill', in: { geo: 'setback' }, params: { ink: 'pink', mode: 'add' } },
      cross: { type: 'polygon', params: { pts: '1040 318 1040 442 1020 350 1062 350', closed: 0 } },
      crossB: { type: 'stroke', in: { geo: 'cross' }, params: { ink: 'blue', mode: 'solid', w: 5 } },
      crossP: { type: 'stroke', in: { geo: 'cross' }, params: { ink: 'pink', mode: 'add', w: 5 } },
      catWin: { type: 'rect', params: { x: 958, y: 578, w: 130, h: 122 } },
      catWinY: { type: 'fill', in: { geo: 'catWin' }, params: { ink: 'yellow', mode: 'solid' } },
      catWinP: { type: 'fill', in: { geo: 'catWin' }, params: { ink: 'pink', mode: 'add', tone: 0.85 } },
      catHead: { type: 'circle', params: { x: '1040 + 1.5*sin(t*0.8)', y: 632, r: 19, n: 32 } },
      catEars: { type: 'polygon', params: { pts: '1024 622 1020 600 1036 614 1044 614 1060 600 1056 622' } },
      catBody: { type: 'ellipse', params: { x: 1038, y: 672, rx: 27, ry: 26, n: 40 } },
      catTail: { type: 'polygon', params: { pts: '1012 680 1000 690 1002 700 1014 698', closed: 0 } },
      cat: { type: 'merge', in: { list: ['catHead', 'catEars', 'catBody'] } },
      catB: { type: 'fill', in: { geo: 'cat' }, params: { ink: 'blue', mode: 'add' } },
      catP: { type: 'fill', in: { geo: 'cat' }, params: { ink: 'pink', mode: 'add' } },
      catTB: { type: 'stroke', in: { geo: 'catTail' }, params: { ink: 'blue', mode: 'add', w: 6 } },
      catTP: { type: 'stroke', in: { geo: 'catTail' }, params: { ink: 'pink', mode: 'add', w: 6 } },
      sill: { type: 'rect', params: { x: 958, y: 696, w: 130, h: 6 } },
      sillB: { type: 'fill', in: { geo: 'sill' }, params: { ink: 'blue', mode: 'solid' } },
      sillP: { type: 'fill', in: { geo: 'sill' }, params: { ink: 'pink', mode: 'add' } },
      marks: { type: 'merge', in: { list: ['skyBT', 'skyPT', 'stars', 'haloC', 'haloY', 'moonC', 'craters', 'leftTop', 'capB', 'capP', 'capLS', 'antennaB', 'antennaP', 'left', 'bigWinY', 'bigWinT', 'lampS', 'lampF', 'lampP',
        'roofB', 'roofP', 'roofG', 'tankF', 'tankP', 'tankLB', 'tankLP', 'hutY', 'hutB', 'hutP', 'setbackB', 'setbackP', 'crossB', 'crossP', 'right', 'catWinY', 'catWinP', 'catB', 'catP', 'catTB', 'catTP', 'sillB', 'sillP'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
