// ferris: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'ferris',
  about: 'a ferris wheel of lights over striped fairground tents, purple to orange night',
  seed: 4,
  transition: null,
  graph: {
    let: { cellBlue: 7, cellPink: 7, cellYellow: 7.5, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      // sky: purple at the top, magenta in the middle, orange-yellow at the ground
      skyTop: { type: 'sky', params: { y: 0, h: 540, blueTop: 0.7, blueBottom: 0.2, pinkTop: 1.0, pinkBottom: 1.0, yellowTop: 0, yellowBottom: 0.3, mottle: 0.2, cell: 7, seed: 4 } },
      skyLow: { type: 'sky', params: { y: 540, h: 540, blueTop: 0.2, blueBottom: 0.0, pinkTop: 1.0, pinkBottom: 0.5, yellowTop: 0.3, yellowBottom: 1.0, mottle: 0.2, cell: 7, seed: 4 } },
      starPts: { type: 'scatter', params: { x: 540, y: 200, r: 700, count: 140 } },
      stars: { type: 'dots', in: { geo: 'starPts' }, params: { ink: 'all', mode: 'cut', r: '0.6+0.9*rand(1)' } },
      // a crescent moon: the outer arc and the inner arc back, joined
      moonOut: { type: 'ellipse', params: { x: 118, y: 148, rx: 52, ry: 52, a0: 81, a1: 309, n: 40 } },
      moonIn: { type: 'ellipse', params: { x: 144, y: 141, rx: 48, ry: 48, a0: 281, a1: 107, n: 32 } },
      moon: { type: 'join', in: { list: ['moonOut', 'moonIn'] }, params: { close: 1 } },
      moonW: { type: 'fill', in: { geo: 'moon' }, params: { ink: 'all', mode: 'cut' } },
      // tents behind the wheel
      tentL: { type: 'ferrisTent', params: { x: 160, y: 690, w: 205, h: 145, stripes: 11 } },
      tentR: { type: 'ferrisTent', params: { x: 985, y: 800, w: 175, h: 120, stripes: 9 } },
      // strings of bulbs draped between the tents
      chainA: { type: 'wave', params: { x0: -10, x1: 160, y: 690, bumps: 1, amp: 30, n: 30 } },
      chainB: { type: 'wave', params: { x0: 160, x1: 420, y: 700, bumps: 1, amp: 40, n: 40 } },
      chainC: { type: 'wave', params: { x0: 985, x1: 1090, y: 790, bumps: 1, amp: 18, n: 20 } },
      chainD: { type: 'wave', params: { x0: 700, x1: 985, y: 800, bumps: 1, amp: 44, n: 40 } },
      chainLow: { type: 'wave', params: { x0: -10, x1: 1090, y: 985, bumps: 5, amp: 22, n: 200 } },
      chains: { type: 'merge', in: { list: ['chainA', 'chainB', 'chainC', 'chainD', 'chainLow'] } },
      chainsH: { type: 'hand', in: { geo: 'chains' }, params: { step: 6, wobble: 1, wave: 80, jitter: 0.3, press: 0.3, taper: 0, overshoot: 0 } },
      chainsS: { type: 'stroke', in: { geo: 'chainsH' }, params: { ink: 'pink', mode: 'solid', w: 1.8, tone: 0.9 } },
      chainPts: { type: 'resample', in: { geo: 'chains' }, params: { step: 22 } },
      chainY: { type: 'dots', in: { geo: 'chainPts' }, params: { ink: 'yellow', mode: 'solid', r: '3.5+1.5*rand(1)' } },
      chainW: { type: 'dots', in: { geo: 'chainPts' }, params: { ink: 'all', mode: 'cut', r: '1.3+0.7*rand(2)' } },
      // booths along the bottom
      booths: { type: 'copy', params: { n: 4, x: '350 + @i*150 + (rand(1)-0.5)*16', y: '1000 + rand(2)*10' }, template: { nodes: {
        body: { type: 'polygon', params: { pts: '-62 20 62 20 62 100 -62 100' } },
        bodyA: { type: 'attr', in: { geo: 'body' }, attrs: { part: 0 } },
        roof: { type: 'wave', params: { x0: -70, x1: 70, y: 22, bumps: 5, amp: -8, n: 50 } },
        peak: { type: 'polygon', params: { pts: '70 22 0 -14 -70 22', closed: 0 } },
        roofS: { type: 'join', in: { list: ['peak', 'roof'] }, params: { close: 1 } },
        roofA: { type: 'attr', in: { geo: 'roofS' }, attrs: { part: 1 } },
        win: { type: 'polygon', params: { pts: '-40 42 40 42 40 76 -40 76' } },
        winA: { type: 'attr', in: { geo: 'win' }, attrs: { part: 2, c: '@i%3' } },
        all: { type: 'merge', in: { list: ['bodyA', 'roofA', 'winA'] } } }, output: 'all' } },
      boothBody: { type: 'filter', in: { geo: 'booths' }, params: { expr: '@part==0' } },
      boothBodyP: { type: 'fill', in: { geo: 'boothBody' }, params: { ink: 'pink', mode: 'solid' } },
      boothBodyB: { type: 'fill', in: { geo: 'boothBody' }, params: { ink: 'blue', mode: 'add', tone: 0.25 } },
      boothRoof: { type: 'filter', in: { geo: 'booths' }, params: { expr: '@part==1' } },
      boothRoofW: { type: 'fill', in: { geo: 'boothRoof' }, params: { ink: 'all', mode: 'cut' } },
      boothRoofP: { type: 'fill', in: { geo: 'boothRoof' }, params: { ink: 'pink', mode: 'add', tone: 0.45 } },
      boothRoofE: { type: 'stroke', in: { geo: 'boothRoof' }, params: { ink: 'blue', mode: 'add', w: 2.5, tone: 0.8 } },
      win0: { type: 'filter', in: { geo: 'booths' }, params: { expr: '@part==2 && @c==0' } },
      win0Y: { type: 'fill', in: { geo: 'win0' }, params: { ink: 'yellow', mode: 'solid' } },
      win1: { type: 'filter', in: { geo: 'booths' }, params: { expr: '@part==2 && @c==1' } },
      win1P: { type: 'fill', in: { geo: 'win1' }, params: { ink: 'pink', mode: 'solid' } },
      win1Y: { type: 'fill', in: { geo: 'win1' }, params: { ink: 'yellow', mode: 'add' } },
      win2: { type: 'filter', in: { geo: 'booths' }, params: { expr: '@part==2 && @c==2' } },
      win2Y: { type: 'fill', in: { geo: 'win2' }, params: { ink: 'yellow', mode: 'solid' } },
      win2P: { type: 'fill', in: { geo: 'win2' }, params: { ink: 'pink', mode: 'add', tone: 0.5 } },
      // the wheel and its tower in front
      wheel: { type: 'ferris', params: { x: 615, y: 412, r: 322, cabins: 16, spokes: 16, spin: 0.06, tower: 575, light: 3.8 } },
      marks: { type: 'merge', in: { list: ['skyTop', 'skyLow', 'stars', 'moonW', 'tentL', 'tentR', 'chainsS', 'chainY', 'chainW',
        'boothBodyP', 'boothBodyB', 'boothRoofW', 'boothRoofP', 'boothRoofE', 'win0Y', 'win1P', 'win1Y', 'win2Y', 'win2P', 'wheel'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
