// fly: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'fly',
  about: 'a crane fly on a grass stem against a big yellow sun',
  seed: 21,
  transition: null,
  graph: {
    let: { cellBlue: 5.6, cellPink: 5.2, cellYellow: 6.2, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      sky: { type: 'sky', params: { y: 0, h: 1080, blueTop: 0.95, blueBottom: 1.0, pinkTop: 0.7, pinkBottom: 0.8, mottle: 0.25, seed: 4 } },
      sunDisc: { type: 'circle', params: { x: 540, y: 500, r: 490, n: 180 } },
      sunH: { type: 'hand', in: { geo: 'sunDisc' }, params: { step: 8, wobble: 3, wave: 200, jitter: 0.6, press: 0, taper: 0, overshoot: 0 } },
      sunY: { type: 'fill', in: { geo: 'sunH' }, params: { ink: 'yellow', mode: 'solid' } },
      sunField: { type: 'field', params: { expr: 'clamp(0.02 + 0.22*pow(clamp(dist(@x,@y,540,500)/490), 5) + 0.5*pow(clamp(dist(@x,@y,540,500)/490), 12) + 0.1*(noise(@x,@y,120,3)-0.5) + 0.22*pow(radial(@x,@y,230,760,400),2) + 0.12*pow(radial(@x,@y,900,600,330),2))' } },
      sunP: { type: 'tint', in: { geo: 'sunH', field: 'sunField' }, params: { ink: 'pink', cell: 7, angle: 0.4 } },
      rimB: { type: 'field', params: { expr: 'clamp(0.9*pow(clamp(dist(@x,@y,540,500)/490), 14))' } },
      sunB: { type: 'tint', in: { geo: 'sunH', field: 'rimB' }, params: { ink: 'blue', cell: 6, angle: 0.26 } },
      greens: { type: 'bellRings', params: { x: 540, y: 520, r0: 300, gap: 48, count: 3, a0: -150, a1: -118, spread: 14, ink: 'blue', mode: 'add', w: 5, wobble: 2, taper: 0.5, seed: 3 } },
      groundLine: { type: 'line', params: { x0: -20, y0: 838, x1: 1100, y1: 838, n: 120 } },
      groundTop: { type: 'wrangle', in: { geo: 'groundLine' }, params: { y: '@y + 26*pow((@x-540)/540, 2) + 4*(noise(@x,0,150,5)-0.5)' } },
      groundFoot: { type: 'polygon', params: { pts: '1100 1100 -20 1100', closed: 0 } },
      ground: { type: 'join', in: { list: ['groundTop', 'groundFoot'] }, params: { close: 1 } },
      groundB: { type: 'fill', in: { geo: 'ground' }, params: { ink: 'blue', mode: 'solid' } },
      groundP: { type: 'fill', in: { geo: 'ground' }, params: { ink: 'pink', mode: 'add', tone: 0.9 } },
      stripes: { type: 'copy', params: { n: 3 }, template: { nodes: {
        l: { type: 'line', params: { x0: -20, y0: '884 + @i*56', x1: 1100, y1: '884 + @i*56', n: 100 } },
        w: { type: 'wrangle', in: { geo: 'l' }, params: { y: '@y + 20*pow((@x-540)/540, 2) + 2*sin(@x/160 + t*0.8 + @i)', w: '10 + 4*noise(@x, @i*30, 200, 8)' } } }, output: 'w' } },
      stripesS: { type: 'stroke', in: { geo: 'stripes' }, params: { ink: 'pink', mode: 'cut' } },
      stem: { type: 'ellipse', params: { x: 540, y: 950, rx: 380, ry: 470, a0: -172, a1: -16, n: 120 } },
      stemW: { type: 'wrangle', in: { geo: 'stem' }, params: { x: '@x + 6*sin(t*0.9)*sin(@v*PI)', w: '5 - 2.5*abs(@v-0.5)' } },
      stemH: { type: 'hand', in: { geo: 'stemW' }, params: { step: 7, wobble: 2, wave: 150, jitter: 0.4, press: 0.3, taper: 0.2, overshoot: 0 } },
      stemS: { type: 'stroke', in: { geo: 'stemH' }, params: { ink: 'all', mode: 'add' } },
      stalks: { type: 'polygon', params: { pts: '520 520 460 560 420 640 470 680', closed: 0 } },
      stalk2: { type: 'polygon', params: { pts: '620 520 650 570 655 640', closed: 0 } },
      stalkAll: { type: 'merge', in: { list: ['stalks', 'stalk2'] } },
      stalkW: { type: 'wrangle', in: { geo: 'stalkAll' }, params: { x: '@x + 3*sin(t*1.1+@v*3)*@v', w: '2.6' } },
      stalkH: { type: 'hand', in: { geo: 'stalkW' }, params: { step: 5, wobble: 1.5, wave: 60, jitter: 0.3, press: 0.3, taper: 0, overshoot: 0 } },
      stalkS: { type: 'stroke', in: { geo: 'stalkH' }, params: { ink: 'all', mode: 'add' } },
      seedPts: { type: 'polygon', params: { pts: '448 566 432 592 424 626 446 594 468 640 636 546 660 570 646 610 668 640 654 656', closed: 0 } },
      seeds: { type: 'copy', in: { points: 'seedPts' }, params: { orient: 0, rot: '-0.6 + 1.3*rand(1)', scale: '0.8 + 0.5*rand(2)' }, template: { nodes: { l: { type: 'lens', params: { len: 13, wid: 9, n: 10 } } }, output: 'l' } },
      seedsF: { type: 'fill', in: { geo: 'seeds' }, params: { ink: 'all', mode: 'add' } },
      blades: { type: 'copy', params: { n: 7 }, template: {
        let: { bx: '80 + @i*150 + rand(1)*70', bh: '70 + 150*rand(2)', lean: '(rand(3)-0.5)*90' },
        nodes: {
          l: { type: 'line', params: { x0: '$bx', y0: 1090, x1: '$bx + $lean', y1: '1090 - $bh', n: 14 } },
          w: { type: 'wrangle', in: { geo: 'l' }, params: { x: '@x + $lean*0.4*@v*@v + 6*@v*@v*sin(t*1.4 + @i)', w: '5*(1-@v) + 0.4' } },
        }, output: 'w' } },
      bladesH: { type: 'hand', in: { geo: 'blades' }, params: { step: 6, wobble: 1.5, wave: 90, jitter: 0.3, press: 0.3, taper: 0, overshoot: 0 } },
      bladesS: { type: 'stroke', in: { geo: 'bladesH' }, params: { ink: 'all', mode: 'add' } },
      fly: { type: 'flyInsect', params: { x: 575, y: '392 + 3*sin(t*2.1)', scale: 1.0, rot: '-0.04 + 0.012*sin(t*2.1)' } },
      marks: { type: 'merge', in: { list: ['sky', 'sunY', 'sunP', 'sunB', 'greens', 'groundB', 'groundP', 'stripesS', 'bladesS', 'stemS', 'stalkS', 'seedsF', 'fly'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
