// frog: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'frog',
  about: 'two frogs croaking under a huge full moon among the reeds',
  seed: 13,
  transition: null,
  graph: {
    let: { cellBlue: 6.5, cellPink: 6.5, cellYellow: 7, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      // purple night: blue fading downward, pink rising, more pink at the bottom left
      sky: { type: 'sky', params: { y: 0, h: 1080, blueTop: 1.0, blueBottom: 0.35, pinkTop: 0.35, pinkBottom: 1.2, mottle: 0.25, cell: 6.5, seed: 4 } },
      skyBox: { type: 'rect', params: { x: 0, y: 0, w: 1080, h: 1080 } },
      fPinkL: { type: 'field', params: { expr: '0.7*clamp(lin(@x,@y,800,300,100,850))' } },
      pinkL: { type: 'tint', in: { geo: 'skyBox', field: 'fPinkL' }, params: { ink: 'pink', cell: 6.5, angle: 0.8 } },
      starPts: { type: 'scatter', params: { x: 540, y: 300, r: 800, count: 140 } },
      stars: { type: 'dots', in: { geo: 'starPts' }, params: { ink: 'all', mode: 'cut', r: '0.6+1.0*rand(1)*(0.7+0.3*sin(t*3+@i))' } },
      // sound rings in the sky, pink, only the upper half
      rings: { type: 'copy', params: { n: 5 }, template: { nodes: { a: { type: 'ellipse', params: { x: 640, y: 570, rx: '480 + @i*52 + 3*sin(t*1.5+@i)', ry: '480 + @i*52 + 3*sin(t*1.5+@i)', a0: -200, a1: 20, n: 120 } } }, output: 'a' } },
      ringsH: { type: 'hand', in: { geo: 'rings' }, params: { step: 8, wobble: 2.5, wave: 150, jitter: 0.5, press: 0.5, taper: 0.4, overshoot: 0 } },
      ringsW: { type: 'wrangle', in: { geo: 'ringsH' }, params: { w: '@pw*2.4' } },
      ringsS: { type: 'stroke', in: { geo: 'ringsW' }, params: { ink: 'pink', mode: 'solid' } },
      moon: { type: 'frogMoon', params: { x: 640, y: 555, r: 435, craters: 0.6, scale: 190, seed: 3, rim: 0.3, cell: 8.5 } },
      // reeds behind the frogs
      c1: { type: 'frogCattail', params: { x: 68, y: 1040, h: 920, lean: -0.02, head: 120, hw: 13, w: 5, seed: 1 } },
      c2: { type: 'frogCattail', params: { x: 190, y: 1040, h: 780, lean: 0.03, head: 130, hw: 14, w: 5, seed: 2 } },
      c3: { type: 'frogCattail', params: { x: 245, y: 1040, h: 560, lean: -0.05, head: 100, hw: 11, w: 4, seed: 3 } },
      c4: { type: 'frogCattail', params: { x: 1000, y: 1040, h: 960, lean: 0.02, head: 150, hw: 15, w: 5, seed: 4 } },
      c5: { type: 'frogCattail', params: { x: 1062, y: 1040, h: 760, lean: 0.06, head: 110, hw: 12, w: 4, seed: 5 } },
      // leaf blades: long tapered lines leaning
      blades: { type: 'polygon', params: { pts: '330 1040 372 520', closed: 0 } },
      blade2: { type: 'polygon', params: { pts: '410 1040 375 600', closed: 0 } },
      blade3: { type: 'polygon', params: { pts: '120 1040 215 640', closed: 0 } },
      blade4: { type: 'polygon', params: { pts: '960 1040 985 420', closed: 0 } },
      bladeAll: { type: 'merge', in: { list: ['blades', 'blade2', 'blade3', 'blade4'] } },
      bladeR: { type: 'resample', in: { geo: 'bladeAll' }, params: { step: 10 } },
      bladeW: { type: 'wrangle', in: { geo: 'bladeR' }, params: { x: '@x + 2*sin(t*0.9+@x*0.02)*@v', w: '9*(1-@v)+1.5' } },
      bladeH: { type: 'hand', in: { geo: 'bladeW' }, params: { step: 8, wobble: 2, wave: 200, jitter: 0.3, press: 0.2, taper: 0, overshoot: 0 } },
      bladeB: { type: 'stroke', in: { geo: 'bladeH' }, params: { ink: 'blue', mode: 'add' } },
      bladeY: { type: 'stroke', in: { geo: 'bladeH' }, params: { ink: 'yellow', mode: 'add' } },
      bladeP: { type: 'stroke', in: { geo: 'bladeH' }, params: { ink: 'pink', mode: 'add', tone: 0.7 } },
      // water at the bottom: blue and pink, lily pads, yellow ripples
      water: { type: 'polygon', params: { pts: '-10 1028 300 1024 700 1030 1090 1026 1090 1090 -10 1090' } },
      waterB: { type: 'fill', in: { geo: 'water' }, params: { ink: 'blue', mode: 'solid' } },
      waterP: { type: 'fill', in: { geo: 'water' }, params: { ink: 'pink', mode: 'add', tone: 0.55 } },
      pads: { type: 'copy', params: { n: 4, x: '150 + @i*280 + (rand(1)-0.5)*60', y: '1052 + rand(2)*14' }, template: { nodes: { e: { type: 'ellipse', params: { x: 0, y: 0, rx: '60+40*rand(3)', ry: '9+5*rand(4)', n: 40 } } }, output: 'e' } },
      padsB: { type: 'fill', in: { geo: 'pads' }, params: { ink: 'blue', mode: 'solid' } },
      padsY: { type: 'fill', in: { geo: 'pads' }, params: { ink: 'yellow', mode: 'add' } },
      padsP: { type: 'fill', in: { geo: 'pads' }, params: { ink: 'pink', mode: 'add', tone: 0.5 } },
      rippleG: { type: 'copy', params: { n: 7, x: '80 + @i*150 + rand(1)*60', y: '1040 + rand(2)*30' }, template: { nodes: { l: { type: 'line', params: { x0: '-20-30*rand(3)', y0: 0, x1: '20+30*rand(3)', y1: 0, n: 2 } } }, output: 'l' } },
      rippleS: { type: 'stroke', in: { geo: 'rippleG' }, params: { ink: 'yellow', mode: 'solid', w: 3 } },
      // frogs: the big one at the left facing right, a smaller one at the right facing left
      big: { type: 'frogling', params: { x: 545, y: 1082, s: 1, flip: 1, sac: 74, spots: 14, green: 0.6, seed: 1 } },
      small: { type: 'frogling', params: { x: 905, y: 1092, s: 0.8, flip: -1, sac: 60, spots: 10, green: 0.6, seed: 2 } },
      // the croak: orange arcs fanning up and to the right from the big frog's mouth, with thin spokes
      croak: { type: 'copy', params: { n: 6, x: '(rand(7)-0.5)*8', y: '(rand(8)-0.5)*8' }, template: { let: { R: '80 + @i*48*(0.92+0.16*rand(5)) + 5*sin(t*3 - @i*0.6)' }, nodes: { a: { type: 'ellipse', params: { x: 600, y: 920, rx: '$R', ry: '$R', a0: '-72 - rand(1)*8', a1: '4 + rand(2)*8', n: 48 } } }, output: 'a' } },
      croakH: { type: 'hand', in: { geo: 'croak' }, params: { step: 5, wobble: 1.5, wave: 80, jitter: 0.5, press: 0.5, taper: 0.5, overshoot: 0 } },
      croakW: { type: 'wrangle', in: { geo: 'croakH' }, params: { w: '@pw*3.2' } },
      croakP: { type: 'stroke', in: { geo: 'croakW' }, params: { ink: 'pink', mode: 'solid' } },
      croakY: { type: 'stroke', in: { geo: 'croakW' }, params: { ink: 'yellow', mode: 'add' } },
      spokes: { type: 'rays', params: { x: 600, y: 920, a0: -62, a1: -8, count: 3, r0: 90, r1: 340 } },
      spokesH: { type: 'hand', in: { geo: 'spokes' }, params: { step: 6, wobble: 2, wave: 100, jitter: 0.4, press: 0.4, taper: 0.5, overshoot: 0 } },
      spokesW: { type: 'wrangle', in: { geo: 'spokesH' }, params: { w: '@pw*0.9' } },
      spokesP: { type: 'stroke', in: { geo: 'spokesW' }, params: { ink: 'pink', mode: 'solid' } },
      spokesY: { type: 'stroke', in: { geo: 'spokesW' }, params: { ink: 'yellow', mode: 'add' } },
      marks: { type: 'merge', in: { list: ['sky', 'pinkL', 'stars', 'ringsS', 'moon', 'c1', 'c2', 'c3', 'c4', 'c5', 'bladeB', 'bladeY', 'bladeP', 'waterB', 'waterP', 'padsB', 'padsY', 'padsP', 'rippleS', 'croakP', 'croakY', 'spokesP', 'spokesY', 'small', 'big'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
