// hummingbird: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'hummingbird',
  about: 'a hummingbird hovering among leaves and pink trumpet flowers',
  seed: 24,
  transition: null,
  graph: {
    let: { cellBlue: 10.5, cellPink: 7.5, cellYellow: 8, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      // yellow-green ground: full yellow, blue dots thickening towards the edges
      page: { type: 'rect', params: { x: -10, y: -10, w: 1100, h: 1100 } },
      pageY: { type: 'fill', in: { geo: 'page' }, params: { ink: 'yellow', mode: 'solid' } },
      pageBf: { type: 'field', params: { expr: 'clamp(0.5 - 0.32*radial(@x,@y,560,480,560) + 0.14*(noise(@x,@y,140,3)-0.5))' } },
      pageB: { type: 'tint', in: { geo: 'page', field: 'pageBf' }, params: { ink: 'blue', cell: 10.5, angle: 0.26 } },
      // dark leaves at the corners, lighter ones in front
      leaf1: { type: 'leaf', params: { x: -40, y: 60, rot: 0.55, len: 330, wid: 200, dark: 1, red: 0.55, hatch: 0, veinInk: 'pink', seed: 1 } },
      leaf2: { type: 'leaf', params: { x: 1110, y: 250, rot: 2.95, len: 280, wid: 180, dark: 1, red: 0.55, hatch: 0, veinInk: 'pink', seed: 2 } },
      leaf3: { type: 'leaf', params: { x: -60, y: 1070, rot: -0.55, len: 400, wid: 230, dark: 1, red: 0.55, hatch: 0, veinInk: 'pink', seed: 3 } },
      leaf4: { type: 'leaf', params: { x: 1110, y: 1070, rot: -2.55, len: 340, wid: 210, dark: 1, red: 0.55, hatch: 0, veinInk: 'pink', seed: 4 } },
      leaf5: { type: 'leaf', params: { x: 40, y: 760, rot: -0.25, len: 190, wid: 80, dark: 0.35, hatch: 0, veinInk: 'pink', seed: 5 } },
      leaf6: { type: 'leaf', params: { x: 150, y: 1095, rot: -1.35, len: 230, wid: 95, dark: 0.35, hatch: 0, veinInk: 'pink', seed: 6 } },
      leaf7: { type: 'leaf', params: { x: 1030, y: 830, rot: 2.75, len: 210, wid: 85, dark: 0.35, hatch: 0, veinInk: 'pink', seed: 7 } },
      leaf8: { type: 'leaf', params: { x: 880, y: 1095, rot: -2.15, len: 260, wid: 160, dark: 1, red: 0.55, hatch: 0, veinInk: 'pink', seed: 8 } },
      leaf9: { type: 'leaf', params: { x: 1100, y: 40, rot: 2.6, len: 200, wid: 110, dark: 1, red: 0.55, hatch: 0, veinInk: 'pink', seed: 9 } },
      flower1: { type: 'trumpet', params: { x: 985, y: 50, rot: -2.25, size: 135, seed: 1 } },
      flower2: { type: 'trumpet', params: { x: 1010, y: 480, rot: 3.05, size: 150, seed: 2 } },
      flower3: { type: 'trumpet', params: { x: 25, y: 790, rot: 0.35, size: 110, seed: 3 } },
      flower4: { type: 'trumpet', params: { x: 950, y: 895, rot: 2.75, size: 160, seed: 4 } },
      // wing blur: a fan of faint blue wings about the shoulder, then the sharp blue wing
      ghosts: { type: 'copy', params: { n: 10, x: 480, y: 300, rot: '-3.35 + @i*0.11 + 0.1*sin(t*31 + @i)' }, template: { nodes: { l: { type: 'line', params: { x0: '40 + 30*rand(1)', y0: 0, x1: '300 + 80*rand(2)', y1: 0, n: 8 } }, w: { type: 'wrangle', in: { geo: 'l' }, params: { w: '(6 + 9*rand(3))*(0.5 + 0.5*sin(@v*PI))' } } }, output: 'w' } },
      ghostsH: { type: 'hand', in: { geo: 'ghosts' }, params: { step: 6, wobble: 2, wave: 80, jitter: 0.5, press: 0.4, taper: 0.5, overshoot: 0 } },
      ghostsC: { type: 'stroke', in: { geo: 'ghostsH' }, params: { ink: 'yellow', mode: 'cut' } },
      ghostsB: { type: 'stroke', in: { geo: 'ghostsH' }, params: { ink: 'blue', mode: 'add', tone: 0.5 } },
      tail: { type: 'polygon', params: { pts: '395 500 415 548 330 612 248 600 268 540 330 500' } },
      tailH: { type: 'hand', in: { geo: 'tail' }, params: { step: 6, wobble: 2, wave: 60, jitter: 0.6, press: 0, taper: 0, overshoot: 0 } },
      tailY: { type: 'fill', in: { geo: 'tailH' }, params: { ink: 'yellow', mode: 'solid' } },
      tailB: { type: 'fill', in: { geo: 'tailH' }, params: { ink: 'blue', mode: 'add', tone: 0.95 } },
      tailLines: { type: 'rays', params: { x: 410, y: 520, a0: 140, a1: 165, count: 3, r0: 30, r1: 160 } },
      tailLinesS: { type: 'stroke', in: { geo: 'tailLines' }, params: { ink: 'all', mode: 'cut', w: 2 } },
      tailLinesC: { type: 'crop', in: { marks: 'tailLinesS', geo: 'tailH' } },
      tailSpots: { type: 'polygon', params: { pts: '262 566 280 598 300 530', closed: 0 } },
      tailSpotsC: { type: 'dots', in: { geo: 'tailSpots' }, params: { ink: 'all', mode: 'cut', r: '5+2*rand(1)' } },
      body: { type: 'ellipse', params: { x: 482, y: 392, rx: 215, ry: 118, rot: -0.72, n: 60 } },
      bodyH: { type: 'hand', in: { geo: 'body' }, params: { step: 7, wobble: 2, wave: 100, jitter: 0.6, press: 0, taper: 0, overshoot: 0 } },
      bodyY: { type: 'fill', in: { geo: 'bodyH' }, params: { ink: 'yellow', mode: 'solid' } },
      bodyBf: { type: 'field', params: { expr: 'clamp(0.55 + 0.4*lin(@x,@y,470,330,470,470) + 0.1*(noise(@x,@y,30,4)-0.5))' } },
      bodyB: { type: 'tint', in: { geo: 'bodyH', field: 'bodyBf' }, params: { ink: 'blue', cell: 6.5, angle: 0.5 } },
      belly: { type: 'ellipse', params: { x: 552, y: 440, rx: 135, ry: 56, rot: -0.75, n: 50 } },
      bellyH: { type: 'hand', in: { geo: 'belly' }, params: { step: 7, wobble: 2, wave: 80, jitter: 0.5, press: 0, taper: 0, overshoot: 0 } },
      bellyC: { type: 'fill', in: { geo: 'bellyH' }, params: { ink: 'all', mode: 'cut' } },
      bellyBf: { type: 'field', params: { expr: 'clamp(0.05 + 0.4*lin(@x,@y,540,400,560,470))' } },
      bellyB: { type: 'tint', in: { geo: 'bellyH', field: 'bellyBf' }, params: { ink: 'blue', cell: 5, angle: 0.3 } },
      wing: { type: 'ellipse', params: { x: 335, y: 190, rx: 205, ry: 64, rot: '0.71 + 0.04*sin(t*31)', n: 60 } },
      wingH: { type: 'hand', in: { geo: 'wing' }, params: { step: 7, wobble: 2, wave: 100, jitter: 0.6, press: 0, taper: 0, overshoot: 0 } },
      wingB: { type: 'fill', in: { geo: 'wingH' }, params: { ink: 'blue', mode: 'solid' } },
      wingPf: { type: 'field', params: { expr: 'clamp(-0.3 + 1.1*lin(@x,@y,300,120,360,230))' } },
      wingP: { type: 'tint', in: { geo: 'wingH', field: 'wingPf' }, params: { ink: 'pink', cell: 6, angle: 0.8 } },
      head: { type: 'circle', params: { x: 618, y: 228, r: 70, n: 48 } },
      headH: { type: 'hand', in: { geo: 'head' }, params: { step: 6, wobble: 1.8, wave: 70, jitter: 0.5, press: 0, taper: 0, overshoot: 0 } },
      headY: { type: 'fill', in: { geo: 'headH' }, params: { ink: 'yellow', mode: 'solid' } },
      headBf: { type: 'field', params: { expr: 'clamp(0.55 + 0.35*lin(@x,@y,580,190,650,270))' } },
      headB: { type: 'tint', in: { geo: 'headH', field: 'headBf' }, params: { ink: 'blue', cell: 6.5, angle: 0.5 } },
      crown: { type: 'ellipse', params: { x: 615, y: 228, rx: 50, ry: 50, a0: 195, a1: 262, n: 14 } },
      crownH: { type: 'hand', in: { geo: 'crown' }, params: { step: 5, wobble: 1, wave: 50, jitter: 0.3, press: 0.3, taper: 0.5, overshoot: 0 } },
      crownY: { type: 'stroke', in: { geo: 'crownH' }, params: { ink: 'yellow', mode: 'solid', w: 7 } },
      glintPt: { type: 'point', params: { x: 596, y: 246 } },
      glint: { type: 'dots', in: { geo: 'glintPt' }, params: { ink: 'all', mode: 'cut', r: 5 } },
      throat: { type: 'ellipse', params: { x: 668, y: 320, rx: 54, ry: 36, rot: -0.55, n: 40 } },
      throatH: { type: 'hand', in: { geo: 'throat' }, params: { step: 6, wobble: 1.5, wave: 60, jitter: 0.5, press: 0, taper: 0, overshoot: 0 } },
      throatP: { type: 'fill', in: { geo: 'throatH' }, params: { ink: 'pink', mode: 'solid' } },
      throatY: { type: 'fill', in: { geo: 'throatH' }, params: { ink: 'yellow', mode: 'add', tone: 0.85 } },
      throatLines: { type: 'copy', params: { n: 4, x: 640, y: 300, rot: -0.55 }, template: { nodes: { l: { type: 'line', params: { x0: '-10 + @i*14', y0: -30, x1: '-4 + @i*14', y1: 30, n: 4 } } }, output: 'l' } },
      throatLinesS: { type: 'stroke', in: { geo: 'throatLines' }, params: { ink: 'pink', mode: 'solid', w: 2.2 } },
      throatLinesC: { type: 'crop', in: { marks: 'throatLinesS', geo: 'throatH' } },
      beak: { type: 'line', params: { x0: 690, y0: 205, x1: 905, y1: 18, n: 10 } },
      beakW: { type: 'wrangle', in: { geo: 'beak' }, params: { w: '12*(1 - 0.6*@v)' } },
      beakH: { type: 'hand', in: { geo: 'beakW' }, params: { step: 6, wobble: 1, wave: 100, jitter: 0.3, press: 0.2, taper: 0.1, overshoot: 0 } },
      beakP: { type: 'stroke', in: { geo: 'beakH' }, params: { ink: 'pink', mode: 'solid' } },
      beakB: { type: 'stroke', in: { geo: 'beakH' }, params: { ink: 'blue', mode: 'add', tone: 0.7 } },
      beakY: { type: 'stroke', in: { geo: 'beakH' }, params: { ink: 'yellow', mode: 'add', tone: 0.6 } },
      eyePt: { type: 'point', params: { x: 642, y: 212 } },
      eye: { type: 'dots', in: { geo: 'eyePt' }, params: { ink: 'all', mode: 'add', r: 10 } },
      eyeGlintPt: { type: 'point', params: { x: 646, y: 208 } },
      eyeGlint: { type: 'dots', in: { geo: 'eyeGlintPt' }, params: { ink: 'all', mode: 'cut', r: 3 } },
      marks: { type: 'merge', in: { list: ['pageY', 'pageB', 'leaf1', 'leaf2', 'leaf3', 'leaf4', 'leaf8', 'leaf9', 'leaf5', 'leaf6', 'leaf7', 'flower1', 'flower2', 'flower3', 'flower4', 'ghostsC', 'ghostsB', 'tailY', 'tailB', 'tailLinesC', 'tailSpotsC', 'bodyY', 'bodyB', 'bellyC', 'bellyB', 'wingB', 'wingP', 'headY', 'headB', 'crownY', 'glint', 'throatP', 'throatY', 'throatLinesC', 'beakP', 'beakB', 'beakY', 'eye', 'eyeGlint'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
