// lighthouse: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'lighthouse',
  about: 'a striped lighthouse in the rain, its beam sweeping a purple sky',
  seed: 13,
  transition: null,
  graph: {
    let: { cellBlue: 9, cellPink: 9, cellYellow: 9.5, angleBlue: 15, anglePink: 45, angleYellow: 0, lampX: 520, lampY: 185 },
    nodes: {
      skyBox: { type: 'rect', params: { x: -10, y: -10, w: 1100, h: 1100 } },
      skyBlue: { type: 'field', params: { expr: 'clamp(0.7 - 0.15*lin(@x,@y,0,0,0,1080) + 0.12*(noise(@x,@y,110,2)-0.5) + 0.25*lin(@x,@y,0,860,0,1000))' } },
      skyB: { type: 'tint', in: { geo: 'skyBox', field: 'skyBlue' }, params: { ink: 'blue', cell: 10, angle: 0.26 } },
      skyPink: { type: 'field', params: { expr: 'clamp(0.12 + 0.55*lin(@x,@y,0,420,0,760) - 0.45*lin(@x,@y,0,860,0,1000) + 0.1*(noise(@x+300,@y,90,3)-0.5))' } },
      skyP: { type: 'tint', in: { geo: 'skyBox', field: 'skyPink' }, params: { ink: 'pink', cell: 10, angle: 0.78 } },
      fog: { type: 'polygon', params: { pts: '-10 462 1100 470 1100 560 -10 552' } },
      fogH: { type: 'hand', in: { geo: 'fog' }, params: { step: 10, wobble: 9, wave: 90, jitter: 2, press: 0, taper: 0, overshoot: 0 } },
      fogC: { type: 'fill', in: { geo: 'fogH' }, params: { ink: 'all', mode: 'cut' } },
      fogEdge: { type: 'field', params: { expr: 'clamp(0.55*pow(abs(@y-511)/48, 2) + 0.12*(noise(@x,@y,50,6)-0.5))' } },
      fogB: { type: 'tint', in: { geo: 'fogH', field: 'fogEdge' }, params: { ink: 'blue', cell: 10, angle: 0.26 } },
      fogPink: { type: 'field', params: { expr: 'clamp(0.4*pow(max(0, @y-511)/48, 2))' } },
      fogP: { type: 'tint', in: { geo: 'fogH', field: 'fogPink' }, params: { ink: 'pink', cell: 10, angle: 0.78 } },
      halo: { type: 'bellRings', params: { x: '$lampX', y: '$lampY', r0: 160, gap: 100, count: 6, a0: -70, a1: 120, spread: 12, ink: 'blue', mode: 'add', w: 40, tone: 0.95, wobble: 3, taper: 0.2, drift: 12, seed: 5 } },
      // beams: two strong ones upward, a faint one down-left
      beamL: { type: 'polygon', params: { pts: '$lampX $lampY -10 -10 -10 190' } },
      beamR: { type: 'polygon', params: { pts: '$lampX $lampY 1100 -30 1100 130' } },
      beams: { type: 'merge', in: { list: ['beamL', 'beamR'] } },
      beamsH: { type: 'hand', in: { geo: 'beams' }, params: { step: 10, wobble: 4, wave: 300, jitter: 1, press: 0, taper: 0, overshoot: 0 } },
      beamsY: { type: 'fill', in: { geo: 'beamsH' }, params: { ink: 'yellow', mode: 'solid' } },
      beamsRim: { type: 'field', params: { expr: 'clamp(0.4*lin(@x,@y,$lampX,$lampY,0,0))' } },
      beamsB: { type: 'tint', in: { geo: 'beamsH', field: 'beamsRim' }, params: { ink: 'blue', cell: 10, angle: 0.26 } },
      faint: { type: 'polygon', params: { pts: '$lampX $lampY -10 320 -10 470' } },
      faintC: { type: 'fill', in: { geo: 'faint' }, params: { ink: 'all', mode: 'cut' } },
      faintField: { type: 'field', params: { expr: 'clamp(0.15 + 0.3*lin(@x,@y,$lampX,$lampY,0,400))' } },
      faintB: { type: 'tint', in: { geo: 'faint', field: 'faintField' }, params: { ink: 'blue', cell: 10, angle: 0.26 } },
      faintY: { type: 'fill', in: { geo: 'faint' }, params: { ink: 'yellow', mode: 'add', tone: 0.12 } },
      // sea and rocks
      sea: { type: 'bellWaves', params: { y: 905, bottom: 1100, bumps: 14, amp: 10, rows: 5, blue: 0.9, pink: 0.3, foam: 3, speckle: 500, speed: 0.8, seed: 8 } },
      rock: { type: 'polygon', params: { pts: '220 1100 260 1010 330 960 400 940 470 920 560 918 640 930 700 960 760 990 840 1040 880 1100' } },
      rockH: { type: 'hand', in: { geo: 'rock' }, params: { step: 8, wobble: 4, wave: 60, jitter: 1.5, press: 0, taper: 0, overshoot: 0 } },
      rockB: { type: 'fill', in: { geo: 'rockH' }, params: { ink: 'blue', mode: 'add' } },
      rockP: { type: 'fill', in: { geo: 'rockH' }, params: { ink: 'pink', mode: 'add', tone: 0.9 } },
      rockY: { type: 'fill', in: { geo: 'rockH' }, params: { ink: 'yellow', mode: 'add', tone: 0.5 } },
      rockPts: { type: 'scatter', in: { geo: 'rockH' }, params: { count: 90 } },
      rockSpeck: { type: 'dots', in: { geo: 'rockPts' }, params: { ink: 'yellow', mode: 'cut', r: '1.5 + 2*rand(1)' } },
      facet1: { type: 'polygon', params: { pts: '300 972 400 940 470 920 440 990 340 1010' } },
      facet2: { type: 'polygon', params: { pts: '600 926 700 960 760 990 700 1010 620 980' } },
      facet3: { type: 'polygon', params: { pts: '240 1030 300 1010 330 1060 260 1100 225 1100' } },
      facets: { type: 'merge', in: { list: ['facet1', 'facet2', 'facet3'] } },
      facetsH: { type: 'hand', in: { geo: 'facets' }, params: { step: 8, wobble: 3, wave: 60, jitter: 1, press: 0, taper: 0, overshoot: 0 } },
      facetsP: { type: 'fill', in: { geo: 'facetsH' }, params: { ink: 'pink', mode: 'cut' } },
      facetsY: { type: 'fill', in: { geo: 'facetsH' }, params: { ink: 'yellow', mode: 'cut' } },
      facetsB: { type: 'fill', in: { geo: 'facetsH' }, params: { ink: 'pink', mode: 'add', tone: 0.5 } },
      cracks: { type: 'polygon', params: { pts: '300 1000 360 1050 380 1100', closed: 0 } },
      cracks2: { type: 'polygon', params: { pts: '700 980 740 1040 800 1100', closed: 0 } },
      cracksAll: { type: 'merge', in: { list: ['cracks', 'cracks2'] } },
      cracksW: { type: 'wrangle', in: { geo: 'cracksAll' }, params: { w: 3 } },
      cracksH: { type: 'hand', in: { geo: 'cracksW' }, params: { step: 6, wobble: 2, wave: 60, jitter: 0.5, press: 0.4, taper: 0.3, overshoot: 0 } },
      cracksS: { type: 'stroke', in: { geo: 'cracksH' }, params: { ink: 'pink', mode: 'cut' } },
      spray: { type: 'polygon', params: { pts: '150 990 190 960 250 960', closed: 0 } },
      spray2: { type: 'polygon', params: { pts: '920 1030 880 990 830 1000', closed: 0 } },
      sprays: { type: 'copy', params: { n: 6 }, template: { nodes: { l: { type: 'polygon', params: { pts: '0 0 -20 -30 -50 -40', closed: 0 } } }, output: 'l' }, in: { points: 'sprayPts' } },
      sprayPts: { type: 'polygon', params: { pts: '200 985 240 975 830 1010 880 1030 150 1040 930 1060', closed: 0 } },
      sprayAll: { type: 'merge', in: { list: ['spray', 'spray2', 'sprays'] } },
      sprayW: { type: 'wrangle', in: { geo: 'sprayAll' }, params: { x: '@x + 6*sin(t*3+@v*4)*@v', w: '5 - 4*@v' } },
      sprayH: { type: 'hand', in: { geo: 'sprayW' }, params: { step: 5, wobble: 1.5, wave: 40, jitter: 0.4, press: 0.4, taper: 0.4, overshoot: 0 } },
      sprayS: { type: 'stroke', in: { geo: 'sprayH' }, params: { ink: 'all', mode: 'cut' } },
      tower: { type: 'lighthouse', params: { x: 520, y: 930 } },
      rainBox: { type: 'rect', params: { x: -10, y: -10, w: 1100, h: 930 } },
      rain: { type: 'lighthouseStreaks', in: { geo: 'rainBox' }, params: { count: 200, angle: 72, spread: 3, len: 80, vary: 0.7, w: 1.2, ink: 'all', mode: 'cut', speed: 900, seed: 1 } },
      rainB: { type: 'lighthouseStreaks', in: { geo: 'rainBox' }, params: { count: 70, angle: 72, spread: 3, len: 70, vary: 0.7, w: 1, ink: 'blue', mode: 'add', speed: 800, seed: 2 } },
      marks: { type: 'merge', in: { list: ['skyB', 'skyP', 'halo', 'fogC', 'fogB', 'fogP', 'faintC', 'faintB', 'faintY', 'beamsY', 'beamsB', 'sea', 'rockB', 'rockP', 'rockY', 'rockSpeck', 'facetsP', 'facetsY', 'facetsB', 'cracksS', 'sprayS', 'tower', 'rain', 'rainB'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
