// main: the film. Every world is a clip with its own local time; the sequence stacks them with hard cuts.
// Reorder the list to change the timing. Flag one clip to play it alone.
export const scene = {
  name: 'main',
  about: 'the film: all worlds in order, hard cuts',
  seed: 1,
  transition: null,
  graph: {
    let: { cellBlue: 5.6, cellPink: 5.2, cellYellow: 6.2, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      fly: { type: 'clip', params: { scene: 'fly', dur: 3, mode: 'cut' } },
      jelly: { type: 'clip', params: { scene: 'jelly', dur: 3, mode: 'cut' } },
      owl: { type: 'clip', params: { scene: 'owl', dur: 3, mode: 'cut' } },
      bell: { type: 'clip', params: { scene: 'bell', dur: 3, mode: 'cut' } },
      lighthouse: { type: 'clip', params: { scene: 'lighthouse', dur: 3, mode: 'cut' } },
      wolf: { type: 'clip', params: { scene: 'wolf', dur: 3, mode: 'cut' } },
      telephone: { type: 'clip', params: { scene: 'telephone', dur: 3, mode: 'cut' } },
      turntable: { type: 'clip', params: { scene: 'turntable', dur: 3, mode: 'cut' } },
      frog: { type: 'clip', params: { scene: 'frog', dur: 3, mode: 'cut' } },
      bats: { type: 'clip', params: { scene: 'bats', dur: 3, mode: 'cut' } },
      wave: { type: 'clip', params: { scene: 'wave', dur: 3, mode: 'cut' } },
      cat: { type: 'clip', params: { scene: 'cat', dur: 3, mode: 'cut' } },
      bee: { type: 'clip', params: { scene: 'bee', dur: 3, mode: 'cut' } },
      radio: { type: 'clip', params: { scene: 'radio', dur: 3, mode: 'cut' } },
      fireworks: { type: 'clip', params: { scene: 'fireworks', dur: 3, mode: 'cut' } },
      hummingbird: { type: 'clip', params: { scene: 'hummingbird', dur: 3, mode: 'cut' } },
      kettle: { type: 'clip', params: { scene: 'kettle', dur: 3, mode: 'cut' } },
      ferris: { type: 'clip', params: { scene: 'ferris', dur: 3, mode: 'cut' } },
      waterfall: { type: 'clip', params: { scene: 'waterfall', dur: 3, mode: 'cut' } },
      bicycle: { type: 'clip', params: { scene: 'bicycle', dur: 3, mode: 'cut' } },
      whale: { type: 'clip', params: { scene: 'whale', dur: 3, mode: 'cut' } },
      piano: { type: 'clip', params: { scene: 'piano', dur: 3, mode: 'cut' } },
      rocket: { type: 'clip', params: { scene: 'rocket', dur: 3, mode: 'cut' } },
      city: { type: 'clip', params: { scene: 'city', dur: 3, mode: 'cut' } },
      saturn: { type: 'clip', params: { scene: 'saturn', dur: 3, mode: 'cut' } },
      balloons: { type: 'clip', params: { scene: 'balloons', dur: 3, mode: 'cut' } },
      volcano: { type: 'clip', params: { scene: 'volcano', dur: 3, mode: 'cut' } },
      telescope: { type: 'clip', params: { scene: 'telescope', dur: 3, mode: 'cut' } },
      campfire: { type: 'clip', params: { scene: 'campfire', dur: 3, mode: 'cut' } },
      sunflowers: { type: 'clip', params: { scene: 'sunflowers', dur: 3, mode: 'cut' } },
      snow: { type: 'clip', params: { scene: 'snow', dur: 3, mode: 'cut' } },
      mountains: { type: 'clip', params: { scene: 'mountains', dur: 3, mode: 'cut' } },
      savanna: { type: 'clip', params: { scene: 'savanna', dur: 3, mode: 'cut' } },
      pond: { type: 'clip', params: { scene: 'pond', dur: 3, mode: 'cut' } },
      seq: { type: 'sequence', in: { list: ['fly', 'jelly', 'owl', 'bell', 'lighthouse', 'wolf', 'telephone', 'turntable', 'frog', 'bats', 'wave', 'cat', 'bee', 'radio', 'fireworks', 'hummingbird', 'kettle', 'ferris', 'waterfall', 'bicycle', 'whale', 'piano', 'rocket', 'city', 'saturn', 'balloons', 'volcano', 'telescope', 'campfire', 'sunflowers', 'snow', 'mountains', 'savanna', 'pond'] }, params: { gap: 0 } },
      stencils: { type: 'rasterize', in: { marks: 'seq' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'seq',
  },
};
