// owl: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'owl',
  about: 'an owl close up against a dark trunk and a dotted wall',
  seed: 8,
  transition: null,
  graph: {
    let: { cellBlue: 5.6, cellPink: 5.2, cellYellow: 6.2, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      // the whole sheet is yellow; the right wall carries big pink dots, the top-right wedge stays clean
      paper: { type: 'rect', params: { x: -10, y: -10, w: 1100, h: 1100 } },
      paperY: { type: 'fill', in: { geo: 'paper' }, params: { ink: 'yellow', mode: 'solid' } },
      wall: { type: 'polygon', params: { pts: '620 -10 1100 -10 1100 1100 620 1100' } },
      wallField: { type: 'field', params: { expr: 'clamp(0.42 + 0.08*(noise(@x,@y,90,2)-0.5) - 0.5*lin(@x,@y,760,40,900,-40))' } },
      wallP: { type: 'tint', in: { geo: 'wall', field: 'wallField' }, params: { ink: 'pink', cell: 13, angle: 0.3 } },
      wedgeBand: { type: 'polygon', params: { pts: '690 -10 760 -10 1100 70 1100 130' } },
      wedgeBandH: { type: 'hand', in: { geo: 'wedgeBand' }, params: { step: 8, wobble: 3, wave: 100, jitter: 0.6, press: 0, taper: 0, overshoot: 0 } },
      wedgeField: { type: 'field', params: { expr: '0.55' } },
      wedgeG: { type: 'tint', in: { geo: 'wedgeBandH', field: 'wedgeField' }, params: { ink: 'blue', cell: 9, angle: 0.5 } },
      // green hatching in the lower right corner
      hatchBox: { type: 'polygon', params: { pts: '700 640 1100 560 1100 1100 640 1100' } },
      hatch: { type: 'lighthouseStreaks', in: { geo: 'hatchBox' }, params: { count: 70, angle: 62, spread: 8, len: 420, vary: 0.4, w: 4, ink: 'blue', mode: 'add', tone: 1, seed: 3 } },
      hatch2: { type: 'lighthouseStreaks', in: { geo: 'hatchBox' }, params: { count: 30, angle: 62, spread: 6, len: 300, vary: 0.5, w: 2.5, ink: 'pink', mode: 'add', tone: 0.7, seed: 5 } },
      // the trunk: near-black green, with a jagged right edge rimmed orange and a green dotted band outside it
      trunk: { type: 'polygon', params: { pts: '380 -10 690 -10 715 60 685 140 730 250 700 330 745 420 715 520 735 600 700 650 755 740 715 830 770 920 735 1000 765 1100 380 1100' } },
      trunkH: { type: 'hand', in: { geo: 'trunk' }, params: { step: 8, wobble: 3, wave: 90, jitter: 1, press: 0, taper: 0, overshoot: 0 } },
      band: { type: 'transform', in: { geo: 'trunkH' }, params: { x: 44 } },
      bandCut: { type: 'fill', in: { geo: 'band' }, params: { ink: 'pink', mode: 'cut' } },
      bandField: { type: 'field', params: { expr: '0.55 + 0.2*(noise(@x,@y,40,9)-0.5)' } },
      bandG: { type: 'tint', in: { geo: 'band', field: 'bandField' }, params: { ink: 'blue', cell: 9, angle: 0.5 } },
      trunkB: { type: 'fill', in: { geo: 'trunkH' }, params: { ink: 'blue', mode: 'add' } },
      trunkP: { type: 'fill', in: { geo: 'trunkH' }, params: { ink: 'pink', mode: 'add', tone: 0.8 } },
      trunkSpeck: { type: 'scatter', in: { geo: 'trunkH' }, params: { count: 120 } },
      trunkSpeckD: { type: 'dots', in: { geo: 'trunkSpeck' }, params: { ink: 'blue', mode: 'cut', r: '1 + 2*rand(1)' } },
      edge: { type: 'polygon', params: { pts: '690 -10 715 60 685 140 730 250 700 330 745 420 715 520 735 600 700 650 755 740 715 830 770 920 735 1000 765 1100', closed: 0 } },
      edgeW: { type: 'wrangle', in: { geo: 'edge' }, params: { w: '5 + 3*noise(@y, 0, 80, 3)' } },
      edgeH: { type: 'hand', in: { geo: 'edgeW' }, params: { step: 7, wobble: 3, wave: 90, jitter: 1, press: 0.4, taper: 0, overshoot: 0 } },
      edgeS: { type: 'stroke', in: { geo: 'edgeH' }, params: { ink: 'blue', mode: 'cut' } },
      edgeDark: { type: 'transform', in: { geo: 'edgeH' }, params: { x: 46 } },
      edgeDarkS: { type: 'stroke', in: { geo: 'edgeDark' }, params: { ink: 'all', mode: 'add', w: 3 } },
      bird: { type: 'owl', params: { x: '215 + 2*sin(t*0.7)', y: '130 + 3*sin(t*0.9)', blink: '1 - 0.04*abs(sin(t*1.7))' } },
      marks: { type: 'merge', in: { list: ['paperY', 'wallP', 'wedgeG', 'hatch', 'hatch2', 'bandCut', 'bandG', 'trunkB', 'trunkP', 'trunkSpeckD', 'edgeS', 'edgeDarkS', 'bird'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
