// radio: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'radio',
  about: 'a vintage tabletop radio in a purple room, sound waves ringing out',
  seed: 23,
  transition: null,
  graph: {
    let: { cellBlue: 8, cellPink: 7.5, cellYellow: 8, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      // the room: navy in the corners, magenta around the radio, a pink floor
      page: { type: 'rect', params: { x: -10, y: -10, w: 1100, h: 1000 } },
      roomBf: { type: 'field', params: { expr: 'clamp(0.9 - 0.6*radial(@x,@y,515,760,720) + 0.2*(noise(@x,@y,120,4)-0.5))' } },
      roomB: { type: 'tint', in: { geo: 'page', field: 'roomBf' }, params: { ink: 'blue', cell: 8, angle: 0.26 } },
      roomPf: { type: 'field', params: { expr: 'clamp(0.55 + 0.6*radial(@x,@y,515,760,760) + 0.2*(noise(@x+300,@y,90,5)-0.5))' } },
      roomP: { type: 'tint', in: { geo: 'page', field: 'roomPf' }, params: { ink: 'pink', cell: 7.5, angle: 0.8 } },
      floor: { type: 'rect', params: { x: -10, y: 988, w: 1100, h: 110 } },
      floorH: { type: 'hand', in: { geo: 'floor' }, params: { step: 8, wobble: 1.5, wave: 120, jitter: 0.4, press: 0, taper: 0, overshoot: 0 } },
      floorP: { type: 'fill', in: { geo: 'floorH' }, params: { ink: 'pink', mode: 'solid', tone: 0.9 } },
      floorBf: { type: 'field', params: { expr: 'clamp(0.25 + 0.45*lin(@x,@y,0,988,0,1080))' } },
      floorB: { type: 'tint', in: { geo: 'floorH', field: 'floorBf' }, params: { ink: 'blue', cell: 8, angle: 0.26 } },
      floorEdge: { type: 'line', params: { x0: -10, y0: 988, x1: 1090, y1: 986, n: 20 } },
      floorEdgeH: { type: 'hand', in: { geo: 'floorEdge' }, params: { step: 8, wobble: 1, wave: 150, jitter: 0.4, press: 0.4, taper: 0, overshoot: 0 } },
      floorEdgeC: { type: 'stroke', in: { geo: 'floorEdgeH' }, params: { ink: 'all', mode: 'cut', w: 3 } },
      // sound waves ringing out from the radio
      ring1: { type: 'wavering', params: { x: 515, y: 720, r: 365, a0: -196, a1: 16, count: 5, span: 40, w: 20, phase: 0, seed: 1 } },
      ring2: { type: 'wavering', params: { x: 515, y: 720, r: 465, a0: -200, a1: 20, count: 6, span: 38, w: 21, phase: 1, seed: 2 } },
      ring3: { type: 'wavering', params: { x: 515, y: 720, r: 565, a0: -206, a1: 26, count: 7, span: 36, w: 22, phase: 2, seed: 3 } },
      ring4: { type: 'wavering', params: { x: 515, y: 720, r: 670, a0: -212, a1: 32, count: 8, span: 33, w: 22, phase: 3, seed: 4 } },
      ring5: { type: 'wavering', params: { x: 515, y: 720, r: 780, a0: -218, a1: 38, count: 9, span: 30, w: 23, phase: 4, seed: 5 } },
      // the cabinet: an arch, orange with dark edges
      arch: { type: 'ellipse', params: { x: 505, y: 600, rx: 240, ry: 315, a0: 180, a1: 360, n: 48 } },
      archFoot: { type: 'polygon', params: { pts: '745 945 265 945', closed: 0 } },
      cabinet: { type: 'join', in: { list: ['arch', 'archFoot'] }, params: { close: 1 } },
      cabinetH: { type: 'hand', in: { geo: 'cabinet' }, params: { step: 8, wobble: 2, wave: 120, jitter: 0.6, press: 0, taper: 0, overshoot: 0 } },
      cabP: { type: 'fill', in: { geo: 'cabinetH' }, params: { ink: 'pink', mode: 'solid', tone: 0.85 } },
      cabY: { type: 'fill', in: { geo: 'cabinetH' }, params: { ink: 'yellow', mode: 'add' } },
      cabBf: { type: 'field', params: { expr: 'clamp(0.75 - 1.1*radial(@x,@y,505,640,300) + 0.15*(noise(@x,@y,30,6)-0.5))' } },
      cabB: { type: 'tint', in: { geo: 'cabinetH', field: 'cabBf' }, params: { ink: 'blue', cell: 6, angle: 0.5 } },
      cabS: { type: 'stroke', in: { geo: 'cabinetH' }, params: { ink: 'all', mode: 'add', w: 6 } },
      // an inner panel, lighter orange, with a dark moulding line round it
      panelFoot: { type: 'polygon', params: { pts: '710 930 300 930', closed: 0 } },
      panel: { type: 'join', in: { list: ['arch2', 'panelFoot'] }, params: { close: 1 } },
      panelY: { type: 'fill', in: { geo: 'panel' }, params: { ink: 'yellow', mode: 'solid' } },
      panelPf: { type: 'field', params: { expr: 'clamp(0.45 + 0.35*lin(@x,@y,0,600,0,930) + 0.15*(noise(@x,@y,30,8)-0.5))' } },
      panelP: { type: 'tint', in: { geo: 'panel', field: 'panelPf' }, params: { ink: 'pink', cell: 6, angle: 0.8 } },
      panelBf: { type: 'field', params: { expr: 'clamp(0.5 - 0.9*radial(@x,@y,505,700,260))' } },
      panelB: { type: 'tint', in: { geo: 'panel', field: 'panelBf' }, params: { ink: 'blue', cell: 6, angle: 0.5 } },
      arch2: { type: 'ellipse', params: { x: 505, y: 600, rx: 205, ry: 275, a0: 180, a1: 360, n: 40 } },
      arch2Foot: { type: 'polygon', params: { pts: '710 930', closed: 0 } },
      arch2Lead: { type: 'polygon', params: { pts: '300 930', closed: 0 } },
      arch2L: { type: 'join', in: { list: ['arch2Lead', 'arch2', 'arch2Foot'] } },
      arch2H: { type: 'hand', in: { geo: 'arch2L' }, params: { step: 7, wobble: 1.5, wave: 100, jitter: 0.5, press: 0.4, taper: 0.2, overshoot: 0 } },
      arch2S: { type: 'stroke', in: { geo: 'arch2H' }, params: { ink: 'all', mode: 'add', w: 4 } },
      // the speaker window: a lighter arch with a sunburst grille
      win: { type: 'ellipse', params: { x: 510, y: 600, rx: 170, ry: 215, a0: 180, a1: 360, n: 40 } },
      winFoot: { type: 'polygon', params: { pts: '680 700 340 700', closed: 0 } },
      window: { type: 'join', in: { list: ['win', 'winFoot'] }, params: { close: 1 } },
      windowH: { type: 'hand', in: { geo: 'window' }, params: { step: 7, wobble: 1.5, wave: 100, jitter: 0.5, press: 0, taper: 0, overshoot: 0 } },
      winY: { type: 'fill', in: { geo: 'windowH' }, params: { ink: 'yellow', mode: 'solid' } },
      winPf: { type: 'field', params: { expr: 'clamp(0.2 + 0.5*lin(@x,@y,0,380,0,700) + 0.15*(noise(@x,@y,25,7)-0.5))' } },
      winP: { type: 'tint', in: { geo: 'windowH', field: 'winPf' }, params: { ink: 'pink', cell: 5.5, angle: 0.8 } },
      winS: { type: 'stroke', in: { geo: 'windowH' }, params: { ink: 'all', mode: 'add', w: 7 } },
      burst: { type: 'rays', params: { x: 512, y: 698, a0: -158, a1: -22, count: 5, r0: 40, r1: 260 } },
      burstW: { type: 'wrangle', in: { geo: 'burst' }, params: { w: '11 + 6*@v' } },
      burstH: { type: 'hand', in: { geo: 'burstW' }, params: { step: 6, wobble: 1.5, wave: 80, jitter: 0.5, press: 0.3, taper: 0, overshoot: 0 } },
      burstS: { type: 'stroke', in: { geo: 'burstH' }, params: { ink: 'all', mode: 'add' } },
      burstC: { type: 'crop', in: { marks: 'burstS', geo: 'windowH' } },
      hub: { type: 'ellipse', params: { x: 512, y: 698, rx: 62, ry: 58, a0: 180, a1: 360, n: 24 } },
      hubFoot: { type: 'polygon', params: { pts: '574 698 450 698', closed: 0 } },
      hubShape: { type: 'join', in: { list: ['hub', 'hubFoot'] }, params: { close: 1 } },
      hubD: { type: 'fill', in: { geo: 'hubShape' }, params: { ink: 'all', mode: 'add' } },
      hubHi: { type: 'ellipse', params: { x: 512, y: 698, rx: 44, ry: 40, a0: 200, a1: 300, n: 12 } },
      hubHiS: { type: 'stroke', in: { geo: 'hubHi' }, params: { ink: 'blue', mode: 'cut', w: 5 } },
      // the dial: a yellow lens with ticks and a red pointer
      dial: { type: 'lens', params: { len: 150, wid: 70, n: 24 } },
      dialT: { type: 'transform', in: { geo: 'dial' }, params: { x: 478, y: 782 } },
      dialH: { type: 'hand', in: { geo: 'dialT' }, params: { step: 6, wobble: 1.2, wave: 80, jitter: 0.4, press: 0, taper: 0, overshoot: 0 } },
      dialY: { type: 'fill', in: { geo: 'dialH' }, params: { ink: 'yellow', mode: 'solid' } },
      dialS: { type: 'stroke', in: { geo: 'dialH' }, params: { ink: 'all', mode: 'add', w: 5 } },
      ticks: { type: 'copy', params: { n: 20, x: '365 + @i*12', y: 772 }, template: { nodes: { l: { type: 'line', params: { x0: 0, y0: 0, x1: 0, y1: '(@i % 5 == 0 ? 14 : 8)', n: 2 } } }, output: 'l' } },
      ticksS: { type: 'stroke', in: { geo: 'ticks' }, params: { ink: 'blue', mode: 'add', w: 1.6 } },
      ticksC: { type: 'crop', in: { marks: 'ticksS', geo: 'dialH' } },
      pointer: { type: 'line', params: { x0: 512, y0: 760, x1: 512, y1: 805, n: 4 } },
      pointerS: { type: 'stroke', in: { geo: 'pointer' }, params: { ink: 'pink', mode: 'solid', w: 4 } },
      // three knobs with a paper glint
      knobPts: { type: 'polygon', params: { pts: '378 882 478 884 578 882', closed: 0 } },
      knobs: { type: 'dots', in: { geo: 'knobPts' }, params: { ink: 'all', mode: 'add', r: '25 + 2*rand(1)' } },
      knobHi: { type: 'wrangle', in: { geo: 'knobPts' }, params: { x: '@x - 8', y: '@y - 8' } },
      knobHiD: { type: 'dots', in: { geo: 'knobHi' }, params: { ink: 'all', mode: 'cut', r: 5 } },
      // the base plinth
      plinth: { type: 'polygon', params: { pts: '228 945 782 945 792 998 220 998' } },
      plinthH: { type: 'hand', in: { geo: 'plinth' }, params: { step: 8, wobble: 1.5, wave: 100, jitter: 0.5, press: 0, taper: 0, overshoot: 0 } },
      plinthP: { type: 'fill', in: { geo: 'plinthH' }, params: { ink: 'pink', mode: 'solid', tone: 0.9 } },
      plinthY: { type: 'fill', in: { geo: 'plinthH' }, params: { ink: 'yellow', mode: 'add', tone: 0.8 } },
      plinthB: { type: 'fill', in: { geo: 'plinthH' }, params: { ink: 'blue', mode: 'add', tone: 0.85 } },
      plinthTop: { type: 'polygon', params: { pts: '228 945 782 945 770 958 240 958' } },
      plinthTopY: { type: 'fill', in: { geo: 'plinthTop' }, params: { ink: 'yellow', mode: 'solid' } },
      plinthS: { type: 'stroke', in: { geo: 'plinthH' }, params: { ink: 'all', mode: 'add', w: 4 } },
      marks: { type: 'merge', in: { list: ['roomB', 'roomP', 'floorP', 'floorB', 'floorEdgeC', 'ring1', 'ring2', 'ring3', 'ring4', 'ring5', 'plinthP', 'plinthY', 'plinthB', 'plinthTopY', 'plinthS', 'cabP', 'cabY', 'cabB', 'cabS', 'panelY', 'panelP', 'panelB', 'arch2S', 'winY', 'winP', 'winS', 'burstC', 'hubD', 'hubHiS', 'dialY', 'dialS', 'ticksC', 'pointerS', 'knobs', 'knobHiD'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
