// savanna: an acacia and two cypresses in silhouette against an orange sunset, striped fields below.
export const scene = {
  name: 'savanna',
  about: 'an acacia and cypresses in silhouette on a savanna at sunset, striped fields in front',
  seed: 41,
  transition: null,
  graph: {
    let: { cellBlue: 7, cellPink: 10, cellYellow: 8, angleBlue: 15, anglePink: 45, angleYellow: 0, vx: 560, vy: 845 },
    nodes: {
      // sky: yellow, with coarse pink dots that thin out into a bright band at the horizon
      skyHi: { type: 'sky', params: { y: 0, h: 560, blueTop: 0, blueBottom: 0, pinkTop: 1.0, pinkBottom: 0.75, yellowTop: 1.0, yellowBottom: 1.0, mottle: 0.12, cell: 10, seed: 6 } },
      skyLo: { type: 'sky', params: { y: 560, h: 300, blueTop: 0, blueBottom: 0, pinkTop: 0.75, pinkBottom: 0.0, yellowTop: 1.0, yellowBottom: 1.0, mottle: 0.1, cell: 10, seed: 7 } },
      // clouds: three mottled dark masses, each a cluster of circles roughened by hand and tinted with noise
      cloud1: { type: 'copy', params: { n: 5, x: '40 + @i*70 + (rand(1)-0.5)*40 + 3*sin(t*0.4)', y: '130 + (rand(2)-0.5)*70' }, template: { nodes: { c: { type: 'circle', params: { x: 0, y: 0, r: '55+45*rand(3)', n: 30 } } }, output: 'c' } },
      cloud2: { type: 'copy', params: { n: 7, x: '400 + @i*45 + (rand(1)-0.5)*60 + 3*sin(t*0.4+1)', y: '260 + (rand(2)-0.5)*180' }, template: { nodes: { c: { type: 'circle', params: { x: 0, y: 0, r: '60+60*rand(3)', n: 30 } } }, output: 'c' } },
      cloud3: { type: 'copy', params: { n: 6, x: '820 + @i*50 + (rand(1)-0.5)*60 + 3*sin(t*0.4+2)', y: '270 + (rand(2)-0.5)*150' }, template: { nodes: { c: { type: 'circle', params: { x: 0, y: 0, r: '55+55*rand(3)', n: 30 } } }, output: 'c' } },
      clouds0: { type: 'merge', in: { list: ['cloud1', 'cloud2', 'cloud3'] } },
      clouds: { type: 'hand', in: { geo: 'clouds0' }, params: { step: 7, wobble: 16, wave: 45, jitter: 3, press: 0, taper: 0, overshoot: 0 } },
      cloudFB: { type: 'field', params: { expr: 'clamp(0.45 + 0.7*noise(@x,@y,28,11) - 0.25*noise(@x+40,@y,9,12))' } },
      cloudsB: { type: 'tint', in: { geo: 'clouds', field: 'cloudFB' }, params: { ink: 'blue', cell: 6, angle: 0.5 } },
      cloudFP: { type: 'field', params: { expr: 'clamp(0.25 + 0.45*noise(@x+200,@y+80,32,13))' } },
      cloudsP: { type: 'tint', in: { geo: 'clouds', field: 'cloudFP' }, params: { ink: 'pink', cell: 6, angle: 1.0 } },
      cloudPts: { type: 'scatter', in: { geo: 'clouds' }, params: { count: 500 } },
      cloudDots: { type: 'dots', in: { geo: 'cloudPts' }, params: { ink: 'all', mode: 'add', tone: 0.9, r: 'rand(1)<0.5 ? 0 : 1.5+2.5*rand(2)' } },
      // the sunset band: paper and pink streaks near the horizon
      streaks: { type: 'copy', params: { n: 6, x: 0, y: '748 + @i*9 + (rand(1)-0.5)*6' }, template: { nodes: { l: { type: 'line', params: { x0: '380+200*rand(1)', y0: 0, x1: '900+150*rand(2)', y1: '(rand(3)-0.5)*6', n: 12 } } }, output: 'l' } },
      streaksH: { type: 'hand', in: { geo: 'streaks' }, params: { step: 8, wobble: 2, wave: 150, jitter: 0.5, press: 0.6, taper: 0.5, overshoot: 6 } },
      streaksW: { type: 'wrangle', in: { geo: 'streaksH' }, params: { w: '@pw*(1.2+2.5*rand(1))' } },
      streaksCut: { type: 'stroke', in: { geo: 'streaksW' }, params: { ink: 'all', mode: 'cut' } },
      streaksP: { type: 'transform', in: { geo: 'streaksW' }, params: { x: 20, y: 6 } },
      streaksPS: { type: 'stroke', in: { geo: 'streaksP' }, params: { ink: 'pink', mode: 'solid', w: 3, tone: 0.9 } },
      // silhouettes: acacia, two cypresses, a bush, the dark ground line
      canopy: { type: 'copy', params: { n: 6, x: '230 + @i*66 + (rand(1)-0.5)*30', y: '620 + (rand(2)-0.5)*50 + 3*sin(t*0.9+@i)' }, template: { nodes: { c: { type: 'ellipse', params: { x: 0, y: 0, rx: '60+30*rand(3)', ry: '42+22*rand(4)', n: 30 } } }, output: 'c' } },
      canopyBase: { type: 'polygon', params: { pts: '215 660 570 665 585 690 500 700 300 700 200 690' } },
      trunk: { type: 'polygon', params: { pts: '382 835 386 735 336 692 344 686 390 716 392 692 446 664 452 671 404 702 404 735 410 835' } },
      cyp1: { type: 'polygon', params: { pts: '78 515 92 560 100 640 98 730 92 830 62 830 54 730 54 640 62 560' } },
      cyp2: { type: 'polygon', params: { pts: '136 585 150 630 158 700 154 830 118 830 114 700 122 630' } },
      bush: { type: 'ellipse', params: { x: 1010, y: 815, rx: 70, ry: 42, n: 30 } },
      hedgeTop: { type: 'wave', params: { x0: -20, x1: 1100, y: 830, bumps: 14, amp: -12, n: 200, abs: 1 } },
      hedgeFoot: { type: 'polygon', params: { pts: '1100 870 -20 870', closed: 0 } },
      hedge: { type: 'join', in: { list: ['hedgeTop', 'hedgeFoot'] }, params: { close: 1 } },
      sil0: { type: 'merge', in: { list: ['canopy', 'canopyBase', 'trunk', 'cyp1', 'cyp2', 'bush', 'hedge'] } },
      sil: { type: 'hand', in: { geo: 'sil0' }, params: { step: 6, wobble: 3, wave: 40, jitter: 1.2, press: 0, taper: 0, overshoot: 0 } },
      silB: { type: 'fill', in: { geo: 'sil' }, params: { ink: 'blue', mode: 'solid' } },
      silP: { type: 'fill', in: { geo: 'sil' }, params: { ink: 'pink', mode: 'add', tone: 0.9 } },
      silY: { type: 'fill', in: { geo: 'sil' }, params: { ink: 'yellow', mode: 'add', tone: 0.9 } },
      // birds
      birds: { type: 'copy', params: { n: 6, x: '990 + (rand(1)-0.5)*120 + 4*sin(t*0.7+@i)', y: '430 + @i*44 + (rand(2)-0.5)*30', scale: '1+0.7*rand(3)' }, template: { nodes: {
        v: { type: 'polygon', params: { pts: '-14 -2 -6 -8 0 0 6 -8 14 -2', closed: 0 } },
        w: { type: 'wrangle', in: { geo: 'v' }, params: { y: '@y + (abs(@x)>3 ? 4*sin(t*9+rand(4)*6) : 0)' } } }, output: 'w' } },
      birdsH: { type: 'hand', in: { geo: 'birds' }, params: { step: 3, wobble: 0.5, wave: 20, jitter: 0.3, press: 0.4, taper: 0.4, overshoot: 0 } },
      birdsS: { type: 'stroke', in: { geo: 'birdsH' }, params: { ink: 'all', mode: 'add', w: 3 } },
      // fields: green ground, a lighter far strip, dark stripes converging on a point behind the hedge
      fieldTop: { type: 'wave', params: { x0: -20, x1: 1100, y: 862, bumps: 3, amp: 6, n: 60, abs: 0 } },
      fieldFoot: { type: 'polygon', params: { pts: '1100 1100 -20 1100', closed: 0 } },
      field: { type: 'join', in: { list: ['fieldTop', 'fieldFoot'] }, params: { close: 1 } },
      fieldP: { type: 'fill', in: { geo: 'field' }, params: { ink: 'pink', mode: 'cut' } },
      fieldY: { type: 'fill', in: { geo: 'field' }, params: { ink: 'yellow', mode: 'add' } },
      fieldFB: { type: 'field', params: { expr: 'clamp(0.25 + 0.5*lin(@x,@y,0,860,0,1080) + 0.15*(noise(@x,@y,60,14)-0.5))' } },
      fieldB: { type: 'tint', in: { geo: 'field', field: 'fieldFB' }, params: { ink: 'blue', cell: 7, angle: 0.26 } },
      stripes: { type: 'rays', params: { x: '$vx', y: '$vy', a0: 12, a1: 168, count: 46, r0: 30, r1: 900 } },
      stripesH: { type: 'hand', in: { geo: 'stripes' }, params: { step: 8, wobble: 3, wave: 120, jitter: 0.6, press: 0.5, taper: 0, overshoot: 0 } },
      stripesW: { type: 'wrangle', in: { geo: 'stripesH' }, params: { w: '@pw*(1.2 + 3*rand(1))*(0.3+@v)' } },
      stripesS0: { type: 'stroke', in: { geo: 'stripesW' }, params: { ink: 'blue', mode: 'add', tone: 1 } },
      stripesP0: { type: 'stroke', in: { geo: 'stripesW' }, params: { ink: 'pink', mode: 'add', tone: 0.6 } },
      stripesP: { type: 'crop', in: { marks: 'stripesP0', geo: 'field' } },
      stripesS: { type: 'crop', in: { marks: 'stripesS0', geo: 'field' } },
      farStrip: { type: 'polygon', params: { pts: '-20 862 1100 862 1100 905 -20 905' } },
      farPts: { type: 'scatter', in: { geo: 'farStrip' }, params: { count: 500 } },
      farDots: { type: 'dots', in: { geo: 'farPts' }, params: { ink: 'blue', mode: 'cut', r: '1+2.5*rand(1)' } },
      marks: { type: 'merge', in: { list: ['skyHi', 'skyLo', 'cloudsB', 'cloudsP', 'cloudDots', 'streaksCut', 'streaksPS', 'silB', 'silP', 'silY', 'birdsS', 'fieldP', 'fieldY', 'fieldB', 'stripesS', 'stripesP', 'farDots'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
