// sunflowers: a field of heads to the horizon, two big blooms in front, the sun low with rays.
export const scene = {
  name: 'sunflowers',
  about: 'a sunflower field under a low sun, two big blooms in front',
  seed: 31,
  transition: null,
  graph: {
    let: { cellBlue: 7, cellPink: 8.5, cellYellow: 7.5, angleBlue: 15, anglePink: 45, angleYellow: 0, hz: 445 },
    nodes: {
      // sky: yellow with pink halftone fading down to the horizon, coarse dots
      sky: { type: 'sky', params: { y: 0, h: 460, blueTop: 0, blueBottom: 0, pinkTop: 1.0, pinkBottom: 0.2, yellowTop: 1.0, yellowBottom: 1.0, mottle: 0.1, cell: 8.5, seed: 3 } },
      rays: { type: 'rays', params: { x: 1010, y: 25, a0: 98, a1: 182, count: 9, r0: 140, r1: 1000 } },
      raysH: { type: 'hand', in: { geo: 'rays' }, params: { step: 8, wobble: 4, wave: 200, jitter: 0.8, press: 0.6, taper: 0.5, overshoot: 0 } },
      raysW: { type: 'wrangle', in: { geo: 'raysH' }, params: { w: '@pw*(1.5+5*rand(1))*(1-@v*0.7)' } },
      raysS: { type: 'stroke', in: { geo: 'raysW' }, params: { ink: 'pink', mode: 'cut' } },
      sun: { type: 'circle', params: { x: 1010, y: 25, r: '112 + 2*sin(t*2)', n: 48 } },
      sunH: { type: 'hand', in: { geo: 'sun' }, params: { step: 6, wobble: 2, wave: 60, jitter: 0.6, press: 0, taper: 0, overshoot: 0 } },
      sunCut: { type: 'fill', in: { geo: 'sunH' }, params: { ink: 'all', mode: 'cut' } },
      // the field: green ground with a paler band right of centre
      groundTop: { type: 'wave', params: { x0: -20, x1: 1100, y: '$hz', bumps: 1, amp: -12, n: 40, abs: 1 } },
      groundFoot: { type: 'polygon', params: { pts: '1100 1100 -20 1100', closed: 0 } },
      ground: { type: 'join', in: { list: ['groundTop', 'groundFoot'] }, params: { close: 1 } },
      groundY: { type: 'fill', in: { geo: 'ground' }, params: { ink: 'yellow', mode: 'solid' } },
      groundFB: { type: 'field', params: { expr: 'clamp(0.5 + 0.35*lin(@x,@y,0,$hz,0,1080) - 0.3*pow(1-abs(@x-760)/260,2)*(abs(@x-760)<260) + 0.2*(noise(@x,@y,50,4)-0.5))' } },
      groundB: { type: 'tint', in: { geo: 'ground', field: 'groundFB' }, params: { ink: 'blue', cell: 7, angle: 0.26 } },
      // rows of heads: far rows dense and small, near rows sparse and big; each head a yellow ring round a dark disc
      rows: { type: 'copy', params: { n: 26 }, template: {
        let: { d: 'pow(@i/@n, 1.7)', y: '$hz + 6 + $d*600', sp: '9 + 84*$d' },
        nodes: {
          ln: { type: 'line', params: { x0: '-40 + (rand(1)-0.5)*$sp', y0: '$y', x1: '1120 + (rand(2)-0.5)*$sp', y1: '$y - 10 + 20*rand(3)', n: 'round(1160/$sp)' } },
          jit: { type: 'wrangle', in: { geo: 'ln' }, params: { x: '@x + (rand(1)-0.5)*$sp*0.7', y: '@y + (rand(2)-0.5)*$sp*0.5 + 2*$d*sin(t*1.5+@x*0.02)' } } }, output: 'jit' } },
      headsRing: { type: 'dots', in: { geo: 'rows' }, params: { ink: 'yellow', mode: 'solid', r: '(4.5 + 22*pow((@y-$hz)/600,1.5))*(0.85+0.3*rand(1))' } },
      headsP: { type: 'dots', in: { geo: 'rows' }, params: { ink: 'pink', mode: 'solid', r: '(3 + 13*pow((@y-$hz)/600,1.5))*(0.85+0.3*rand(1))' } },
      headsB: { type: 'dots', in: { geo: 'rows' }, params: { ink: 'blue', mode: 'add', tone: 1, r: '(3 + 13*pow((@y-$hz)/600,1.5))*(0.85+0.3*rand(1))' } },
      headsY: { type: 'dots', in: { geo: 'rows' }, params: { ink: 'yellow', mode: 'add', tone: 1, r: '(3 + 13*pow((@y-$hz)/600,1.5))*(0.85+0.3*rand(1))' } },
      // stems and leaves of the two big blooms
      stemL: { type: 'line', params: { x0: 150, y0: 380, x1: 130, y1: 1100, n: 20 } },
      stemR: { type: 'line', params: { x0: 860, y0: 980, x1: 800, y1: 1100, n: 8 } },
      stems: { type: 'merge', in: { list: ['stemL', 'stemR'] } },
      stemsH: { type: 'hand', in: { geo: 'stems' }, params: { step: 8, wobble: 3, wave: 200, jitter: 0.5, press: 0.2, taper: 0, overshoot: 0 } },
      stemsY: { type: 'stroke', in: { geo: 'stemsH' }, params: { ink: 'yellow', mode: 'solid', w: 24 } },
      stemsB: { type: 'stroke', in: { geo: 'stemsH' }, params: { ink: 'blue', mode: 'add', w: 24, tone: 0.8 } },
      stemsHi: { type: 'transform', in: { geo: 'stemsH' }, params: { x: -6 } },
      stemsHiS: { type: 'stroke', in: { geo: 'stemsHi' }, params: { ink: 'blue', mode: 'cut', w: 4 } },
      leaf1: { type: 'ellipse', params: { x: 110, y: 800, rx: 215, ry: 120, rot: 1.05, n: 60 } },
      leaf2: { type: 'ellipse', params: { x: 290, y: 940, rx: 130, ry: 72, rot: -0.35, n: 50 } },
      leaf3: { type: 'ellipse', params: { x: 620, y: 1030, rx: 160, ry: 75, rot: 0.15, n: 50 } },
      leaves0: { type: 'merge', in: { list: ['leaf1', 'leaf2', 'leaf3'] } },
      leaves: { type: 'wrangle', in: { geo: 'leaves0' }, params: { x: '@x + 3*sin(t*1.1+@y*0.01)', y: '@y' } },
      leavesH: { type: 'hand', in: { geo: 'leaves' }, params: { step: 7, wobble: 6, wave: 80, jitter: 0.8, press: 0, taper: 0, overshoot: 0 } },
      leavesY: { type: 'fill', in: { geo: 'leavesH' }, params: { ink: 'yellow', mode: 'solid' } },
      leafFB: { type: 'field', params: { expr: 'clamp(0.32 + 0.25*(noise(@x,@y,40,9)-0.5) + 0.2*lin(@x,@y,0,700,0,1080))' } },
      leavesB: { type: 'tint', in: { geo: 'leavesH', field: 'leafFB' }, params: { ink: 'blue', cell: 7, angle: 0.26 } },
      leavesS: { type: 'stroke', in: { geo: 'leavesH' }, params: { ink: 'blue', mode: 'add', w: 3 } },
      veins1: { type: 'rays', params: { x: 230, y: 700, a0: 110, a1: 175, count: 6, r0: 20, r1: 320 } },
      veins2: { type: 'rays', params: { x: 170, y: 960, a0: -30, a1: 25, count: 5, r0: 20, r1: 260 } },
      veins3: { type: 'rays', params: { x: 470, y: 1030, a0: -25, a1: 25, count: 5, r0: 20, r1: 320 } },
      veins: { type: 'merge', in: { list: ['veins1', 'veins2', 'veins3'] } },
      veinsH: { type: 'hand', in: { geo: 'veins' }, params: { step: 7, wobble: 4, wave: 120, jitter: 0.6, press: 0.5, taper: 0.6, overshoot: 0 } },
      veinsS0: { type: 'stroke', in: { geo: 'veinsH' }, params: { ink: 'blue', mode: 'cut', w: 6 } },
      veinsS: { type: 'crop', in: { marks: 'veinsS0', geo: 'leavesH' } },
      // the blooms
      bloomL: { type: 'sunflower', params: { x: 165, y: 300, r: 106, rot: 0.2, petals: 24, seeds: 300, seed: 2 } },
      bloomR: { type: 'sunflower', params: { x: 860, y: 900, r: 118, rot: -0.15, petals: 26, seeds: 340, seed: 5 } },
      marks: { type: 'merge', in: { list: ['sky', 'raysS', 'sunCut', 'groundY', 'groundB', 'headsRing', 'headsP', 'headsB', 'headsY', 'stemsY', 'stemsB', 'stemsHiS', 'leavesY', 'leavesB', 'leavesS', 'veinsS', 'bloomL', 'bloomR'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
