// telescope: a radio dish listening to a spiral galaxy in a pink-purple night.
export const scene = {
  name: 'telescope',
  about: 'a radio telescope dish under a purple night sky with a spiral galaxy',
  seed: 17,
  transition: null,
  graph: {
    let: { cellBlue: 7, cellPink: 7, cellYellow: 7.5, angleBlue: 15, anglePink: 45, angleYellow: 0, fx: 525, fy: 350 },
    nodes: {
      // sky: navy at the top, magenta at the horizon
      skyHi: { type: 'sky', params: { y: 0, h: 560, blueTop: 1.0, blueBottom: 0.95, pinkTop: 0.95, pinkBottom: 0.9, mottle: 0.3, cell: 7, seed: 4 } },
      skyLo: { type: 'sky', params: { y: 560, h: 320, blueTop: 0.95, blueBottom: 0.1, pinkTop: 0.85, pinkBottom: 1.0, mottle: 0.2, cell: 7, seed: 5 } },
      // a paler diagonal band of milky way: paper cut dots along a line
      skyBox: { type: 'rect', params: { x: 0, y: 0, w: 1080, h: 860 } },
      starPts: { type: 'scatter', in: { geo: 'skyBox' }, params: { count: 650 } },
      stars: { type: 'dots', in: { geo: 'starPts' }, params: { ink: 'all', mode: 'cut', r: '(rand(1)<0.12 ? 2.2+1.4*rand(2) : 0.8+1.2*rand(2))*(0.8+0.2*sin(t*4+rand(3)*20))' } },
      dustBand: { type: 'polygon', params: { pts: '-20 250 300 -20 700 -20 -20 620' } },
      dustPts: { type: 'scatter', in: { geo: 'dustBand' }, params: { count: 500 } },
      dust: { type: 'dots', in: { geo: 'dustPts' }, params: { ink: 'all', mode: 'cut', r: '0.8+1.6*rand(1)' } },
      starY: { type: 'scatter', in: { geo: 'skyBox' }, params: { count: 60 } },
      starYD: { type: 'dots', in: { geo: 'starY' }, params: { ink: 'yellow', mode: 'solid', r: '1.2+1.4*rand(1)' } },
      // ground: a wavy blue plain, a pink track, darker below
      groundTop: { type: 'wave', params: { x0: -20, x1: 1100, y: 850, bumps: 3, amp: 18, n: 80, abs: 0 } },
      groundFoot: { type: 'polygon', params: { pts: '1100 1100 -20 1100', closed: 0 } },
      ground: { type: 'join', in: { list: ['groundTop', 'groundFoot'] }, params: { close: 1 } },
      groundY: { type: 'fill', in: { geo: 'ground' }, params: { ink: 'yellow', mode: 'cut' } },
      groundFB: { type: 'field', params: { expr: 'clamp(0.85 + 0.15*lin(@x,@y,0,850,0,1080) + 0.25*(noise(@x,@y,60,8)-0.5))' } },
      groundB: { type: 'tint', in: { geo: 'ground', field: 'groundFB' }, params: { ink: 'blue', cell: 7, angle: 0.26 } },
      groundFP: { type: 'field', params: { expr: 'clamp(0.45 + 0.35*lin(@x,@y,0,900,0,1080) + 0.2*(noise(@x+50,@y,80,9)-0.5))' } },
      groundP: { type: 'tint', in: { geo: 'ground', field: 'groundFP' }, params: { ink: 'pink', cell: 7, angle: 0.26 } },
      track: { type: 'wave', params: { x0: -20, x1: 1100, y: 995, bumps: 4, amp: 9, n: 90, abs: 0 } },
      trackH: { type: 'hand', in: { geo: 'track' }, params: { step: 6, wobble: 3, wave: 120, jitter: 0.5, press: 0.4, taper: 0, overshoot: 0 } },
      trackS: { type: 'stroke', in: { geo: 'trackH' }, params: { ink: 'pink', mode: 'solid', w: 5 } },
      // the galaxy: two spiral arms, a yellow core, a stream of pink motes towards the dish
      arms: { type: 'copy', params: { n: 2, x: 835, y: 210, rot: '@i*PI + 0.03*t' }, template: { nodes: {
        ln: { type: 'line', params: { x0: 0, y0: 0, x1: 1, y1: 0, n: 40 } },
        sp: { type: 'wrangle', in: { geo: 'ln' }, params: { x: '(16+165*@v)*cos(@v*3.3)', y: '(16+165*@v)*sin(@v*3.3)*0.7', w: '34*(1-@v)+4' } } }, output: 'sp' } },
      armsH: { type: 'hand', in: { geo: 'arms' }, params: { step: 5, wobble: 1.5, wave: 60, jitter: 0.6, press: 0.4, taper: 0.2, overshoot: 0 } },
      armsP: { type: 'stroke', in: { geo: 'armsH' }, params: { ink: 'pink', mode: 'solid', tone: 0.85 } },
      armsYW: { type: 'wrangle', in: { geo: 'armsH' }, params: { w: '@pw*0.4' } },
      armsY: { type: 'stroke', in: { geo: 'armsYW' }, params: { ink: 'yellow', mode: 'add', tone: 0.9 } },
      armsPts: { type: 'resample', in: { geo: 'arms' }, params: { step: 7 } },
      armDots: { type: 'dots', in: { geo: 'armsPts' }, params: { ink: 'pink', mode: 'solid', r: 'rand(1)<0.4 ? 0 : 2+4*rand(2)*(1-@v*0.5)' } },
      haloPts: { type: 'scatter', params: { x: 835, y: 210, r: 190, count: 160 } },
      haloD: { type: 'dots', in: { geo: 'haloPts' }, params: { ink: 'pink', mode: 'solid', r: '1+2.5*rand(1)' } },
      core: { type: 'circle', params: { x: 835, y: 210, r: 30, n: 24 } },
      coreH: { type: 'hand', in: { geo: 'core' }, params: { step: 5, wobble: 3, wave: 40, jitter: 1, press: 0, taper: 0, overshoot: 0 } },
      coreY: { type: 'fill', in: { geo: 'coreH' }, params: { ink: 'yellow', mode: 'solid' } },
      coreP: { type: 'circle', params: { x: 835, y: 210, r: 7, n: 16 } },
      corePD: { type: 'fill', in: { geo: 'coreP' }, params: { ink: 'pink', mode: 'add' } },
      streamG: { type: 'ellipse', params: { x: 760, y: 330, rx: 130, ry: 60, rot: -0.3, a0: 90, a1: 220, n: 60 } },
      streamPts: { type: 'resample', in: { geo: 'streamG' }, params: { step: 8 } },
      streamD: { type: 'dots', in: { geo: 'streamPts' }, params: { ink: 'pink', mode: 'solid', r: '(rand(1)<0.4 ? 0 : 1.2+2.4*rand(2))' } },
      // signal arcs fanning from the feed towards the galaxy
      sig: { type: 'copy', params: { n: 4 }, template: { nodes: {
        arc: { type: 'ellipse', params: { x: '$fx', y: '$fy', rx: '80+60*@i + 4*sin(t*5+@i)', ry: '80+60*@i + 4*sin(t*5+@i)', a0: '-88+@i*4', a1: '-22-@i*3', n: 24 } },
        w: { type: 'wrangle', in: { geo: 'arc' }, params: { w: '14*sin(@v*PI)+2' } } }, output: 'w' } },
      sigH: { type: 'hand', in: { geo: 'sig' }, params: { step: 5, wobble: 1, wave: 50, jitter: 0.4, press: 0.3, taper: 0, overshoot: 0 } },
      sigP: { type: 'transform', in: { geo: 'sigH' }, params: { x: -5, y: 3 } },
      sigPS: { type: 'stroke', in: { geo: 'sigP' }, params: { ink: 'pink', mode: 'add' } },
      sigS: { type: 'stroke', in: { geo: 'sigH' }, params: { ink: 'yellow', mode: 'solid' } },
      // far dishes
      d1: { type: 'telescopeDishlet', params: { x: 765, y: 790, r: 52, tilt: -0.6, stem: 60 } },
      d2: { type: 'telescopeDishlet', params: { x: 885, y: 830, r: 44, tilt: -0.55, stem: 50 } },
      d3: { type: 'telescopeDishlet', params: { x: 1010, y: 860, r: 36, tilt: -0.5, stem: 42 } },
      // pedestal: navy A-frame with pink braces
      legs: { type: 'polygon', params: { pts: '215 1000 275 760 300 780 245 1000', closed: 1 } },
      legs2: { type: 'polygon', params: { pts: '445 1000 405 780 430 770 475 1000', closed: 1 } },
      legsG: { type: 'merge', in: { list: ['legs', 'legs2'] } },
      legsB: { type: 'fill', in: { geo: 'legsG' }, params: { ink: 'blue', mode: 'solid' } },
      legsP: { type: 'fill', in: { geo: 'legsG' }, params: { ink: 'pink', mode: 'add', tone: 0.7 } },
      brace: { type: 'polygon', params: { pts: '250 850 455 960 240 960 440 850 215 1000 470 1000', closed: 0 } },
      braceH: { type: 'hand', in: { geo: 'brace' }, params: { step: 6, wobble: 1.5, wave: 80, jitter: 0.5, press: 0.3, taper: 0, overshoot: 4 } },
      braceS: { type: 'stroke', in: { geo: 'braceH' }, params: { ink: 'pink', mode: 'solid', w: 3.5 } },
      // the dish: a navy back rim, a paper face with blue and pink shading, a grid, a solid rim
      dishBack: { type: 'ellipse', params: { x: 397, y: 648, rx: 348, ry: 178, rot: 0.48, n: 120 } },
      dishBackB: { type: 'fill', in: { geo: 'dishBack' }, params: { ink: 'blue', mode: 'solid' } },
      dishBackP: { type: 'fill', in: { geo: 'dishBack' }, params: { ink: 'pink', mode: 'add', tone: 0.85 } },
      dish: { type: 'ellipse', params: { x: 385, y: 630, rx: 345, ry: 175, rot: 0.48, n: 120 } },
      dishCut: { type: 'fill', in: { geo: 'dish' }, params: { ink: 'all', mode: 'cut' } },
      dishFB: { type: 'field', params: { expr: 'clamp(0.05 + 0.95*pow(lin(@x,@y,250,540,640,820),1.6) + 0.35*pow(lin(@x,@y,380,560,120,430),3) + 0.15*(noise(@x,@y,50,3)-0.5))' } },
      dishB: { type: 'tint', in: { geo: 'dish', field: 'dishFB' }, params: { ink: 'blue', cell: 7, angle: 0.26 } },
      dishFP: { type: 'field', params: { expr: 'clamp(0.9*pow(lin(@x,@y,330,580,110,440),2.5))' } },
      dishP: { type: 'tint', in: { geo: 'dish', field: 'dishFP' }, params: { ink: 'pink', cell: 7, angle: 0.78 } },
      rings: { type: 'copy', params: { n: 4, x: 385, y: 630, scale: '0.22+0.21*@i' }, template: { nodes: { e: { type: 'ellipse', params: { x: 0, y: 0, rx: 345, ry: 175, rot: 0.48, n: 80 } } }, output: 'e' } },
      spokes: { type: 'rays', params: { x: 0, y: 0, a0: 0, a1: 330, count: 12, r0: 30, r1: 420 } },
      spokesT: { type: 'transform', in: { geo: 'spokes' }, params: { x: 385, y: 630, rot: 0.48, sx: 1, sy: 0.507 } },
      grid: { type: 'merge', in: { list: ['rings', 'spokesT'] } },
      gridH: { type: 'hand', in: { geo: 'grid' }, params: { step: 6, wobble: 1.5, wave: 70, jitter: 0.5, press: 0.4, taper: 0, overshoot: 0 } },
      gridS0: { type: 'stroke', in: { geo: 'gridH' }, params: { ink: 'blue', mode: 'add', w: 2.4 } },
      gridS: { type: 'crop', in: { marks: 'gridS0', geo: 'dish' } },
      rimH: { type: 'hand', in: { geo: 'dish' }, params: { step: 6, wobble: 1.2, wave: 90, jitter: 0.4, press: 0.4, taper: 0, overshoot: 0 } },
      rimS: { type: 'stroke', in: { geo: 'rimH' }, params: { ink: 'blue', mode: 'solid', w: 7 } },
      rimP: { type: 'transform', in: { geo: 'rimH' }, params: { x: 3, y: -2 } },
      rimPS: { type: 'stroke', in: { geo: 'rimP' }, params: { ink: 'pink', mode: 'add', w: 3 } },
      // feed struts: a pink shadow under a paper line, and the feed itself
      struts: { type: 'polygon', params: { pts: '100 440 $fx $fy 690 765 $fx $fy 390 790', closed: 0 } },
      strutsH: { type: 'hand', in: { geo: 'struts' }, params: { step: 6, wobble: 1, wave: 100, jitter: 0.3, press: 0.2, taper: 0, overshoot: 3 } },
      strutsP: { type: 'transform', in: { geo: 'strutsH' }, params: { x: 4, y: 3 } },
      strutsPS: { type: 'stroke', in: { geo: 'strutsP' }, params: { ink: 'pink', mode: 'solid', w: 4 } },
      strutsB: { type: 'transform', in: { geo: 'strutsH' }, params: { x: -3, y: -2 } },
      strutsBS: { type: 'stroke', in: { geo: 'strutsB' }, params: { ink: 'blue', mode: 'solid', w: 3 } },
      strutsS: { type: 'stroke', in: { geo: 'strutsH' }, params: { ink: 'all', mode: 'cut', w: 3.5 } },
      feed: { type: 'polygon', params: { pts: '$fx-14 $fy-8 $fx+8 $fy-20 $fx+16 $fy+4 $fx-4 $fy+16' } },
      feedB: { type: 'fill', in: { geo: 'feed' }, params: { ink: 'blue', mode: 'solid' } },
      feedP: { type: 'fill', in: { geo: 'feed' }, params: { ink: 'pink', mode: 'add' } },
      marks: { type: 'merge', in: { list: ['skyHi', 'skyLo', 'dust', 'stars', 'starYD', 'groundY', 'groundB', 'groundP', 'trackS', 'armsP', 'armsY', 'haloD', 'armDots', 'coreY', 'corePD', 'streamD', 'sigPS', 'sigS', 'd1', 'd2', 'd3', 'legsB', 'legsP', 'braceS', 'dishBackB', 'dishBackP', 'dishCut', 'dishB', 'dishP', 'gridS', 'rimS', 'rimPS', 'strutsPS', 'strutsBS', 'strutsS', 'feedB', 'feedP'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
