// turntable: scene data. Params may be numbers or expressions of t, u, iris.
export const scene = {
  name: 'turntable',
  about: 'a record spinning on green felt, seen from above',
  seed: 13,
  transition: null,
  graph: {
    let: { cellBlue: 5.6, cellPink: 5.2, cellYellow: 6.2, angleBlue: 15, anglePink: 45, angleYellow: 0 },
    nodes: {
      felt: { type: 'sky', params: { y: 0, h: 1080, blueTop: 0.44, blueBottom: 0.42, pinkTop: 0.04, pinkBottom: 0.08, yellowTop: 1.0, yellowBottom: 1.0, mottle: 0.25, cell: 6, seed: 4 } },
      record: { type: 'vinyl', params: { x: 445, y: 590, r: 445, spin: '-0.05 + t*0.5', grooves: 8, label: 150 } },
      scratchA: { type: 'ellipse', params: { x: 445, y: 590, rx: 470, ry: 470, a0: 240, a1: 262, n: 12 } },
      scratchAH: { type: 'hand', in: { geo: 'scratchA' }, params: { step: 6, wobble: 1.5, wave: 60, jitter: 0.4, press: 0.5, taper: 0.8, overshoot: 4 } },
      scratchAS: { type: 'stroke', in: { geo: 'scratchAH' }, params: { ink: 'blue', mode: 'add', w: 2.5 } },
      arm: { type: 'tonearm', params: { x: 915, y: 200, tipX: 752, tipY: 762, r: 76, w: 22, sway: 2 } },
      dotL: { type: 'circle', params: { x: 100, y: 1010, r: 26, n: 40 } },
      dotR: { type: 'circle', params: { x: 990, y: 960, r: 25, n: 40 } },
      dotP: { type: 'circle', params: { x: 910, y: 965, r: 29, n: 40 } },
      dotsW: { type: 'merge', in: { list: ['dotL', 'dotR'] } },
      dotsWH: { type: 'hand', in: { geo: 'dotsW' }, params: { step: 5, wobble: 1, wave: 40, jitter: 0.3, press: 0, taper: 0, overshoot: 0 } },
      dotsShP: { type: 'transform', in: { geo: 'dotsWH' }, params: { x: 6, y: 5 } },
      dotsShPk: { type: 'fill', in: { geo: 'dotsShP' }, params: { ink: 'pink', mode: 'add', tone: 0.8 } },
      dotsCut: { type: 'fill', in: { geo: 'dotsWH' }, params: { ink: 'all', mode: 'cut' } },
      dotPH: { type: 'hand', in: { geo: 'dotP' }, params: { step: 5, wobble: 1, wave: 40, jitter: 0.3, press: 0, taper: 0, overshoot: 0 } },
      dotPS: { type: 'fill', in: { geo: 'dotPH' }, params: { ink: 'pink', mode: 'solid' } },
      scratchB: { type: 'ellipse', params: { x: 1010, y: 860, rx: 130, ry: 130, a0: 105, a1: 165, n: 14 } },
      scratchBH: { type: 'hand', in: { geo: 'scratchB' }, params: { step: 6, wobble: 1.2, wave: 60, jitter: 0.4, press: 0.5, taper: 0.8, overshoot: 4 } },
      scratchBS: { type: 'stroke', in: { geo: 'scratchBH' }, params: { ink: 'blue', mode: 'add', w: 2.5 } },
      marks: { type: 'merge', in: { list: ['felt', 'record', 'scratchAS', 'arm', 'dotsShPk', 'dotsCut', 'dotPS', 'scratchBS'] } },
      stencils: { type: 'rasterize', in: { marks: 'marks' } },
      print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
    },
    output: 'print',
    marks: 'marks',
  },
};
