// Scenes are graphs of catalog nodes and library subnets. Every param may be an expression of
// t (seconds since start), u (seconds since this cycle's iris opened) and iris (mask scale 0..1).

export const SCENES = {
  jelly: {
    name: 'jelly',
    about: 'glowing pink jellyfish rising through dark water',
    seed: 5,
    transition: { type: 'iris', open: 0.17, hold: 0.5, close: 0.17, gap: 0.3 },
    graph: {
      // the screens are shared by the tints in the geometry and by the print
      let: { cellBlue: 5.6, cellPink: 5.2, cellYellow: 6.2, angleBlue: 15, anglePink: 45, angleYellow: 0 },
      nodes: {
        disc: { type: 'circle', params: { x: 660, y: 535, r: 313 } },
        water: { type: 'water', params: {} },
        stars: { type: 'stars', params: { count: 260 } },
        'small-left': { type: 'jellyfish', params: { x: 420, y: 660, r: 64, rot: -0.05, tentacles: 12, length: 2.6, bob: 5 } },
        'small-right': { type: 'jellyfish', params: { x: 905, y: 600, r: 52, rot: 0.08, tentacles: 11, length: 2.8, bob: 4 } },
        big: { type: 'jellyfish', params: { x: 674, y: '358 - 10*u', r: 140, tentacles: 24, length: 3.0, curl: 1.3, bob: 6 } },
        bubble: { type: 'bubble', params: { x: 540, y: 542, r: 21 } },
        world: { type: 'merge', in: { list: ['water', 'stars', 'small-left', 'small-right', 'big', 'bubble'] } },
        worldClip: { type: 'clip', in: { marks: 'world', geo: 'disc' } },
        // iris: a mask circle scaled about the pivot (540, 542); the world underneath never moves
        irisC: { type: 'circle', params: { x: '540 + iris*120', y: '542 - iris*7', r: 'max(0, iris*318 - 5)', n: 90 } },
        irisMask: { type: 'mask', in: { geo: 'irisC' } },
        ringC: { type: 'circle', params: { x: '540 + iris*120', y: '542 - iris*7', r: 'iris*318 - 2', n: 180 }, when: 'iris > 0.06' },
        ring: { type: 'wrangle', in: { geo: 'ringC' }, params: {
          x: '@x + cos(@a)*(1.6*sin(@a*5+1) + 1.2*sin(@a*11+4) + (rand(@i)-0.5)*1.4)',
          y: '@y + sin(@a)*(1.6*sin(@a*5+1) + 1.2*sin(@a*11+4) + (rand(@i)-0.5)*1.4)' } },
        ringB: { type: 'stroke', in: { geo: 'ring' }, params: { ink: 'blue', w: 7 } },
        ringY: { type: 'stroke', in: { geo: 'ring' }, params: { ink: 'yellow', w: 3, tone: 0.5 } },
        marks: { type: 'merge', in: { list: ['worldClip', 'irisMask', 'ringB', 'ringY'] } },
        // compositing: paint the marks onto three stencils, then print
        stencils: { type: 'rasterize', in: { marks: 'marks' } },
        print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: {
          blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
      },
      output: 'print',
      marks: 'marks',
    },
  },

  // ---- fireworks over a harbour: full bleed, hard cut ----
  fireworks: {
    name: 'fireworks',
    about: 'fireworks over a harbour at night',
    seed: 3,
    transition: { type: 'cut', open: 0, hold: 0.25, close: 0, gap: 0 },
    graph: {
      let: { cellBlue: 5.6, cellPink: 5.2, cellYellow: 6.2, angleBlue: 15, anglePink: 45, angleYellow: 0 },
      nodes: {
        sky: { type: 'sky', params: { y: 0, h: 700, blueTop: 1.0, blueBottom: 0.95, pinkTop: 0.75, pinkBottom: 0.6, mottle: 0.3, seed: 3 } },
        starPts: { type: 'scatter', params: { x: 540, y: 300, r: 700, count: 160 } },
        stars: { type: 'dots', in: { geo: 'starPts' }, params: { ink: 'all', mode: 'cut', r: '0.8+1.2*rand(1)' } },
        water: { type: 'sky', params: { y: 700, h: 380, blueTop: 1.0, blueBottom: 1.0, pinkTop: 0.75, pinkBottom: 0.65, mottle: 0.2, seed: 9 } },
        waterBox: { type: 'rect', params: { x: 0, y: 705, w: 1080, h: 375 } },
        glintY: { type: 'scatter', in: { geo: 'waterBox' }, params: { count: 260 } },
        glintYL: { type: 'copy', in: { points: 'glintY' }, params: { orient: 0, x: '(rand(3)-0.5)*14*sin(t*2.5+rand(4)*6)' }, template: { nodes: { l: { type: 'line', params: { x0: '-8-40*rand(1)', y0: 0, x1: '8+40*rand(1)', y1: 0, n: 2 } } }, output: 'l' } },
        glintYS: { type: 'stroke', in: { geo: 'glintYL' }, params: { ink: 'yellow', mode: 'solid', w: 4 } },
        glintP: { type: 'scatter', in: { geo: 'waterBox' }, params: { count: 180 } },
        glintPL: { type: 'copy', in: { points: 'glintP' }, params: { orient: 0, x: '(rand(3)-0.5)*14*sin(t*2.2+rand(4)*6)' }, template: { nodes: { l: { type: 'line', params: { x0: '-6-30*rand(1)', y0: 0, x1: '6+30*rand(1)', y1: 0, n: 2 } } }, output: 'l' } },
        glintPS: { type: 'stroke', in: { geo: 'glintPL' }, params: { ink: 'pink', mode: 'solid', w: 4 } },
        glintW: { type: 'scatter', in: { geo: 'waterBox' }, params: { count: 120 } },
        glintWL: { type: 'copy', in: { points: 'glintW' }, params: { orient: 0, x: '(rand(3)-0.5)*14*sin(t*2.8+rand(4)*6)' }, template: { nodes: { l: { type: 'line', params: { x0: '-5-24*rand(1)', y0: 0, x1: '5+24*rand(1)', y1: 0, n: 2 } } }, output: 'l' } },
        glintWS: { type: 'stroke', in: { geo: 'glintWL' }, params: { ink: 'all', mode: 'cut', w: 3.5 } },
        skyline: { type: 'polygon', params: { pts: '-10 705 -10 668 60 668 60 658 130 658 130 690 200 690 200 672 300 672 300 660 330 660 330 690 480 690 480 672 560 672 560 655 640 655 640 690 700 690 700 670 800 670 800 690 900 690 900 660 960 660 960 672 1090 672 1090 705' } },
        skylineB: { type: 'fill', in: { geo: 'skyline' }, params: { ink: 'blue', mode: 'add' } },
        skylineP: { type: 'fill', in: { geo: 'skyline' }, params: { ink: 'pink', mode: 'add' } },
        skylineY: { type: 'fill', in: { geo: 'skyline' }, params: { ink: 'yellow', mode: 'cut' } },
        crane: { type: 'polygon', params: { pts: '770 480 770 660 900 660 900 480 770 480 900 390 930 390 940 430 770 430 770 480', closed: 0 } },
        craneS: { type: 'stroke', in: { geo: 'crane' }, params: { ink: 'blue', mode: 'add', w: 3 } },
        craneP: { type: 'stroke', in: { geo: 'crane' }, params: { ink: 'pink', mode: 'add', w: 3 } },
        windows: { type: 'scatter', in: { geo: 'skyline' }, params: { count: 18 } },
        windowsD: { type: 'dots', in: { geo: 'windows' }, params: { ink: 'yellow', mode: 'solid', r: 2.5 } },
        b1: { type: 'burst', params: { x: 290, y: 300, r: 245, ink: 'yellow', rays: 96, knob: 1.2, trail: 1.3 } },
        b2: { type: 'burst', params: { x: 790, y: 250, r: 215, ink: 'pink', rays: 90, knob: 0.9, trail: 1.4 } },
        b3: { type: 'burst', params: { x: 655, y: 540, r: 105, ink: 'all', mode: 'cut', rays: 70, knob: 0.7, trail: 0.6 } },
        b4: { type: 'burst', params: { x: 85, y: 560, r: 85, ink: 'pink', rays: 55, knob: 0.8, trail: 0 } },
        b5: { type: 'burst', params: { x: 1000, y: 540, r: 90, ink: 'yellow', rays: 60, knob: 0.6, trail: 0.5 } },
        boat1: { type: 'polygon', params: { pts: '210 935 230 915 300 905 420 910 500 900 640 905 660 900 640 960 260 970' } },
        mast1: { type: 'polygon', params: { pts: '462 560 462 905', closed: 0 } },
        sail1: { type: 'polygon', params: { pts: '462 600 420 640 462 660 462 600 520 700 462 720', closed: 0 } },
        boat2: { type: 'polygon', params: { pts: '740 790 760 770 800 768 830 774 860 770 880 790 930 795 925 815 745 815' } },
        cabin2: { type: 'polygon', params: { pts: '770 770 775 745 830 745 835 770' } },
        boats: { type: 'merge', in: { list: ['boat1', 'boat2', 'cabin2'] } },
        boatsB: { type: 'fill', in: { geo: 'boats' }, params: { ink: 'blue', mode: 'solid' } },
        boatsP: { type: 'fill', in: { geo: 'boats' }, params: { ink: 'pink', mode: 'add' } },
        rig: { type: 'merge', in: { list: ['mast1', 'sail1'] } },
        rigB: { type: 'stroke', in: { geo: 'rig' }, params: { ink: 'blue', mode: 'solid', w: 3 } },
        rigP: { type: 'stroke', in: { geo: 'rig' }, params: { ink: 'pink', mode: 'add', w: 3 } },
        lamps: { type: 'polygon', params: { pts: '790 758 812 758', closed: 0 } },
        lampsD: { type: 'dots', in: { geo: 'lamps' }, params: { ink: 'yellow', mode: 'solid', r: 5 } },
        dot: { type: 'dot', params: {} },
        marks: { type: 'merge', in: { list: ['sky', 'stars', 'water', 'glintYS', 'glintPS', 'glintWS', 'skylineY', 'skylineB', 'skylineP', 'craneS', 'craneP', 'windowsD', 'b1', 'b2', 'b3', 'b4', 'b5', 'boatsB', 'boatsP', 'rigB', 'rigP', 'lampsD', 'dot'] } },
        stencils: { type: 'rasterize', in: { marks: 'marks' } },
        print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
      },
      output: 'print',
      marks: 'marks',
    },
  },

  // ---- mountains at sunset: sky gradient, sun rings, layered ridges, treelines, fog ----
  mountains: {
    name: 'mountains',
    about: 'sunset behind layered mountains and firs',
    seed: 11,
    transition: { type: 'cut', open: 0, hold: 0.125, close: 0, gap: 0 },
    graph: {
      let: { cellBlue: 7, cellPink: 7, cellYellow: 7.5, angleBlue: 15, anglePink: 45, angleYellow: 0 },
      nodes: {
        sky: { type: 'sky', params: { y: 0, h: 520, blueTop: 0.12, blueBottom: 0.0, pinkTop: 0.95, pinkBottom: 0.3, yellowTop: 0.1, yellowBottom: 0.75, mottle: 0.15, cell: 7, seed: 5 } },
        skyBox: { type: 'rect', params: { x: 0, y: 0, w: 1080, h: 520 } },
        sunField: { type: 'field', params: { expr: '0.9*radial(@x,@y,640,430,470)' } },
        sunHaze: { type: 'tint', in: { geo: 'skyBox', field: 'sunField' }, params: { ink: 'yellow', cell: 7, angle: 0.1 } },
        rings: { type: 'copy', params: { n: 7 }, template: { nodes: { c: { type: 'circle', params: { x: 640, y: 420, r: '95 + @i*52', n: 120 } } }, output: 'c' } },
        ringsS: { type: 'stroke', in: { geo: 'rings' }, params: { ink: 'yellow', mode: 'solid', w: 2.2 } },
        sunGlow: { type: 'circle', params: { x: 640, y: 420, r: 84 } },
        sunGlowY: { type: 'fill', in: { geo: 'sunGlow' }, params: { ink: 'yellow', mode: 'solid' } },
        sun: { type: 'circle', params: { x: 640, y: 420, r: 68 } },
        sunW: { type: 'fill', in: { geo: 'sun' }, params: { ink: 'all', mode: 'cut' } },
        bird1: { type: 'polygon', params: { pts: '272 202 286 192 298 202 310 192 326 204', closed: 0 } },
        bird2: { type: 'polygon', params: { pts: '344 246 352 240 358 246 364 240 372 247', closed: 0 } },
        birds: { type: 'merge', in: { list: ['bird1', 'bird2'] } },
        birdsS: { type: 'stroke', in: { geo: 'birds' }, params: { ink: 'blue', mode: 'solid', w: 2.5 } },
        r1: { type: 'ridge', params: { y: 470, bottom: 1100, amp: 110, scale: 260, seed: 3, blue: 0.3, pink: 0.55, fade: 0.5, cell: 7 } },
        r2: { type: 'ridge', params: { y: 560, bottom: 1100, amp: 130, scale: 200, seed: 8, blue: 0.4, pink: 0.6, fade: 0.4, cell: 7 } },
        r3: { type: 'ridge', params: { y: 650, bottom: 1100, amp: 120, scale: 170, seed: 21, blue: 0.7, pink: 0.55, fade: 0.3, cell: 7 } },
        t1: { type: 'treeline', params: { y: 760, bottom: 1100, count: 46, height: 120, vary: 0.6, seed: 4, mode: 'add' } },
        fogBox: { type: 'polygon', params: { pts: '-20 790 1100 790 1100 880 -20 880' } },
        fogCut: { type: 'fill', in: { geo: 'fogBox' }, params: { ink: 'all', mode: 'cut' } },
        fogTint: { type: 'ridge', params: { y: 790, bottom: 880, amp: 0, blue: 0.35, pink: 0.35, fade: 0, cell: 7 } },
        t2: { type: 'treeline', params: { y: 950, bottom: 1100, count: 40, height: 150, vary: 0.35, seed: 13, mode: 'add' } },
        bottomBox: { type: 'polygon', params: { pts: '-20 960 1100 960 1100 1100 -20 1100' } },
        bottomPts: { type: 'scatter', in: { geo: 'bottomBox' }, params: { count: 220 } },
        bottomDots: { type: 'dots', in: { geo: 'bottomPts' }, params: { ink: 'all', mode: 'cut', r: '0.6+1.2*rand(1)' } },
        dot: { type: 'dot', params: {} },
        marks: { type: 'merge', in: { list: ['sky', 'sunHaze', 'ringsS', 'sunGlowY', 'sunW', 'birdsS', 'r1', 'r2', 'r3', 't1', 'fogCut', 'fogTint', 't2', 'bottomDots', 'dot'] } },
        stencils: { type: 'rasterize', in: { marks: 'marks' } },
        print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
      },
      output: 'print',
      marks: 'marks',
    },
  },

  // ---- snowflakes on a magenta night ----
  snow: {
    name: 'snow',
    about: 'snowflakes drifting on a magenta night',
    seed: 7,
    transition: { type: 'cut', open: 0, hold: 0.125, close: 0, gap: 0 },
    graph: {
      let: { cellBlue: 5.6, cellPink: 5.2, cellYellow: 6.2, angleBlue: 15, anglePink: 45, angleYellow: 0 },
      nodes: {
        sky: { type: 'sky', params: { y: 0, h: 1080, blueTop: 0.85, blueBottom: 0.3, pinkTop: 0.8, pinkBottom: 1.0, yellowTop: 0, yellowBottom: 0.5, mottle: 0.35, seed: 2 } },
        bigA: { type: 'flake', params: { x: 900, y: 60, r: 280, rot: 0.5, arms: 6, branches: 2, width: 5, ink: 'pink', mode: 'solid', tone: 0.5, halo: 0, core: 0 } },
        bigB: { type: 'flake', params: { x: 120, y: 880, r: 260, rot: -0.3, arms: 6, branches: 2, width: 5, ink: 'pink', mode: 'solid', tone: 0.5, halo: 0, core: 0 } },
        bigC: { type: 'flake', params: { x: 1060, y: 620, r: 220, rot: 0.2, arms: 6, branches: 2, width: 5, ink: 'pink', mode: 'solid', tone: 0.5, halo: 0, core: 0 } },
        starPts: { type: 'scatter', params: { x: 540, y: 540, r: 800, count: 260 } },
        stars: { type: 'dots', in: { geo: 'starPts' }, params: { ink: 'all', mode: 'cut', r: '0.7+1.3*rand(1)' } },
        sparkPts: { type: 'scatter', params: { x: 540, y: 540, r: 780, count: 22 } },
        sparks: { type: 'copy', in: { points: 'sparkPts' }, params: { orient: 0, scale: '0.6+0.8*rand(2)' }, template: { nodes: {
          a: { type: 'polygon', params: { pts: '-8 0 8 0', closed: 0 } }, b: { type: 'polygon', params: { pts: '0 -8 0 8', closed: 0 } }, ab: { type: 'merge', in: { list: ['a', 'b'] } } }, output: 'ab' } },
        sparksS: { type: 'stroke', in: { geo: 'sparks' }, params: { ink: 'all', mode: 'cut', w: 1.6 } },
        main: { type: 'flake', params: { x: '590 + 4*sin(t*0.9)', y: '410 + 6*sin(t*0.7)', r: 235, rot: '-0.35 + 0.02*sin(t*0.5)', arms: 6, branches: 3, width: 1 } },
        web: { type: 'webflake', params: { x: 100, y: 180, r: 92, rot: 0.3, rings: 5, spokes: 12 } },
        small: { type: 'flake', params: { x: 990, y: 940, r: 95, rot: 0.2, arms: 6, branches: 3, width: 1.2 } },
        spool: { type: 'polygon', params: { pts: '880 560 890 555 960 640 950 645' } },
        spoolEnds: { type: 'polygon', params: { pts: '870 575 905 545 940 625 980 660', closed: 0 } },
        spoolS: { type: 'fill', in: { geo: 'spool' }, params: { ink: 'all', mode: 'cut' } },
        spoolE: { type: 'stroke', in: { geo: 'spoolEnds' }, params: { ink: 'all', mode: 'cut', w: 5 } },
        dot: { type: 'dot', params: {} },
        marks: { type: 'merge', in: { list: ['sky', 'bigA', 'bigB', 'bigC', 'stars', 'sparksS', 'main', 'web', 'small', 'spoolS', 'spoolE', 'dot'] } },
        stencils: { type: 'rasterize', in: { marks: 'marks' } },
        print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
      },
      output: 'print',
      marks: 'marks',
    },
  },

  // ---- main: the composition. Shots of the other scenes in film order ----
  main: {
    name: 'main',
    about: 'the film: shots of every world',
    seed: 1,
    transition: null,
    duration: 2.3,
    graph: {
      let: { cellBlue: 5.6, cellPink: 5.2, cellYellow: 6.2, angleBlue: 15, anglePink: 45, angleYellow: 0 },
      nodes: {
        s1: { type: 'shot', params: { scene: 'jelly', at: 0, dur: 1.14, mode: 'iris' } },
        s2: { type: 'shot', params: { scene: 'fireworks', at: 1.3, dur: 0.25, mode: 'cut' } },
        s3: { type: 'shot', params: { scene: 'snow', at: 1.55, dur: 0.125, mode: 'cut' } },
        s4: { type: 'shot', params: { scene: 'mountains', at: 1.675, dur: 0.125, mode: 'cut' } },
        s5: { type: 'shot', params: { scene: 'jelly', at: 1.9, dur: 0.4, mode: 'iris' } },
        marks: { type: 'merge', in: { list: ['s1', 's2', 's3', 's4', 's5'] } },
        stencils: { type: 'rasterize', in: { marks: 'marks' } },
        print: { type: 'risoPrint', in: { stencils: 'stencils' }, params: { blueCell: '$cellBlue', pinkCell: '$cellPink', yellowCell: '$cellYellow', blueAngle: '$angleBlue', pinkAngle: '$anglePink', yellowAngle: '$angleYellow' } },
      },
      output: 'print',
      marks: 'marks',
    },
  },
};

